// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nsxt
{
    public static class GetPolicyEdgeCluster
    {
        public static Task<GetPolicyEdgeClusterResult> InvokeAsync(GetPolicyEdgeClusterArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetPolicyEdgeClusterResult>("nsxt:index/getPolicyEdgeCluster:getPolicyEdgeCluster", args ?? new GetPolicyEdgeClusterArgs(), options.WithVersion());
    }


    public sealed class GetPolicyEdgeClusterArgs : Pulumi.InvokeArgs
    {
        [Input("description")]
        public string? Description { get; set; }

        [Input("displayName")]
        public string? DisplayName { get; set; }

        [Input("id")]
        public string? Id { get; set; }

        [Input("sitePath")]
        public string? SitePath { get; set; }

        public GetPolicyEdgeClusterArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetPolicyEdgeClusterResult
    {
        public readonly string Description;
        public readonly string DisplayName;
        public readonly string Id;
        public readonly string Path;
        public readonly string? SitePath;

        [OutputConstructor]
        private GetPolicyEdgeClusterResult(
            string description,

            string displayName,

            string id,

            string path,

            string? sitePath)
        {
            Description = description;
            DisplayName = displayName;
            Id = id;
            Path = path;
            SitePath = sitePath;
        }
    }
}
