// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nsxt
{
    public static class GetPolicyVM
    {
        public static Task<GetPolicyVMResult> InvokeAsync(GetPolicyVMArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetPolicyVMResult>("nsxt:index/getPolicyVM:getPolicyVM", args ?? new GetPolicyVMArgs(), options.WithVersion());
    }


    public sealed class GetPolicyVMArgs : Pulumi.InvokeArgs
    {
        [Input("biosId")]
        public string? BiosId { get; set; }

        [Input("description")]
        public string? Description { get; set; }

        [Input("displayName")]
        public string? DisplayName { get; set; }

        [Input("externalId")]
        public string? ExternalId { get; set; }

        [Input("instanceId")]
        public string? InstanceId { get; set; }

        public GetPolicyVMArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetPolicyVMResult
    {
        public readonly string BiosId;
        public readonly string Description;
        public readonly string DisplayName;
        public readonly string ExternalId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string InstanceId;

        [OutputConstructor]
        private GetPolicyVMResult(
            string biosId,

            string description,

            string displayName,

            string externalId,

            string id,

            string instanceId)
        {
            BiosId = biosId;
            Description = description;
            DisplayName = displayName;
            ExternalId = externalId;
            Id = id;
            InstanceId = instanceId;
        }
    }
}
