// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nsxt
{
    public partial class LBTCPMonitor : Pulumi.CustomResource
    {
        /// <summary>
        /// Description of this resource
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The display name of this resource. Defaults to ID if not set
        /// </summary>
        [Output("displayName")]
        public Output<string> DisplayName { get; private set; } = null!;

        /// <summary>
        /// Number of consecutive checks that must fail before marking it down
        /// </summary>
        [Output("fallCount")]
        public Output<int?> FallCount { get; private set; } = null!;

        /// <summary>
        /// The frequency at which the system issues the monitor check (in seconds)
        /// </summary>
        [Output("interval")]
        public Output<int?> Interval { get; private set; } = null!;

        /// <summary>
        /// If the monitor port is specified, it would override pool member port setting for healthcheck. A port range is not
        /// supported
        /// </summary>
        [Output("monitorPort")]
        public Output<string?> MonitorPort { get; private set; } = null!;

        /// <summary>
        /// Expected data, if specified, can be anywhere in the response and it has to be a string, regular expressions are not
        /// supported
        /// </summary>
        [Output("receive")]
        public Output<string?> Receive { get; private set; } = null!;

        /// <summary>
        /// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
        /// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
        /// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
        /// </summary>
        [Output("revision")]
        public Output<int> Revision { get; private set; } = null!;

        /// <summary>
        /// Number of consecutive checks that must pass before marking it up
        /// </summary>
        [Output("riseCount")]
        public Output<int?> RiseCount { get; private set; } = null!;

        /// <summary>
        /// If both send and receive are not specified, then just a TCP connection is established (3-way handshake) to validate
        /// server is healthy, no data is sent.
        /// </summary>
        [Output("send")]
        public Output<string?> Send { get; private set; } = null!;

        /// <summary>
        /// Set of opaque identifiers meaningful to the user
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<Outputs.LBTCPMonitorTag>> Tags { get; private set; } = null!;

        /// <summary>
        /// Number of seconds the target has to respond to the monitor request
        /// </summary>
        [Output("timeout")]
        public Output<int?> Timeout { get; private set; } = null!;


        /// <summary>
        /// Create a LBTCPMonitor resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public LBTCPMonitor(string name, LBTCPMonitorArgs? args = null, CustomResourceOptions? options = null)
            : base("nsxt:index/lBTCPMonitor:LBTCPMonitor", name, args ?? new LBTCPMonitorArgs(), MakeResourceOptions(options, ""))
        {
        }

        private LBTCPMonitor(string name, Input<string> id, LBTCPMonitorState? state = null, CustomResourceOptions? options = null)
            : base("nsxt:index/lBTCPMonitor:LBTCPMonitor", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing LBTCPMonitor resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static LBTCPMonitor Get(string name, Input<string> id, LBTCPMonitorState? state = null, CustomResourceOptions? options = null)
        {
            return new LBTCPMonitor(name, id, state, options);
        }
    }

    public sealed class LBTCPMonitorArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description of this resource
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The display name of this resource. Defaults to ID if not set
        /// </summary>
        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// Number of consecutive checks that must fail before marking it down
        /// </summary>
        [Input("fallCount")]
        public Input<int>? FallCount { get; set; }

        /// <summary>
        /// The frequency at which the system issues the monitor check (in seconds)
        /// </summary>
        [Input("interval")]
        public Input<int>? Interval { get; set; }

        /// <summary>
        /// If the monitor port is specified, it would override pool member port setting for healthcheck. A port range is not
        /// supported
        /// </summary>
        [Input("monitorPort")]
        public Input<string>? MonitorPort { get; set; }

        /// <summary>
        /// Expected data, if specified, can be anywhere in the response and it has to be a string, regular expressions are not
        /// supported
        /// </summary>
        [Input("receive")]
        public Input<string>? Receive { get; set; }

        /// <summary>
        /// Number of consecutive checks that must pass before marking it up
        /// </summary>
        [Input("riseCount")]
        public Input<int>? RiseCount { get; set; }

        /// <summary>
        /// If both send and receive are not specified, then just a TCP connection is established (3-way handshake) to validate
        /// server is healthy, no data is sent.
        /// </summary>
        [Input("send")]
        public Input<string>? Send { get; set; }

        [Input("tags")]
        private InputList<Inputs.LBTCPMonitorTagArgs>? _tags;

        /// <summary>
        /// Set of opaque identifiers meaningful to the user
        /// </summary>
        public InputList<Inputs.LBTCPMonitorTagArgs> Tags
        {
            get => _tags ?? (_tags = new InputList<Inputs.LBTCPMonitorTagArgs>());
            set => _tags = value;
        }

        /// <summary>
        /// Number of seconds the target has to respond to the monitor request
        /// </summary>
        [Input("timeout")]
        public Input<int>? Timeout { get; set; }

        public LBTCPMonitorArgs()
        {
        }
    }

    public sealed class LBTCPMonitorState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description of this resource
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The display name of this resource. Defaults to ID if not set
        /// </summary>
        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// Number of consecutive checks that must fail before marking it down
        /// </summary>
        [Input("fallCount")]
        public Input<int>? FallCount { get; set; }

        /// <summary>
        /// The frequency at which the system issues the monitor check (in seconds)
        /// </summary>
        [Input("interval")]
        public Input<int>? Interval { get; set; }

        /// <summary>
        /// If the monitor port is specified, it would override pool member port setting for healthcheck. A port range is not
        /// supported
        /// </summary>
        [Input("monitorPort")]
        public Input<string>? MonitorPort { get; set; }

        /// <summary>
        /// Expected data, if specified, can be anywhere in the response and it has to be a string, regular expressions are not
        /// supported
        /// </summary>
        [Input("receive")]
        public Input<string>? Receive { get; set; }

        /// <summary>
        /// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
        /// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
        /// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
        /// </summary>
        [Input("revision")]
        public Input<int>? Revision { get; set; }

        /// <summary>
        /// Number of consecutive checks that must pass before marking it up
        /// </summary>
        [Input("riseCount")]
        public Input<int>? RiseCount { get; set; }

        /// <summary>
        /// If both send and receive are not specified, then just a TCP connection is established (3-way handshake) to validate
        /// server is healthy, no data is sent.
        /// </summary>
        [Input("send")]
        public Input<string>? Send { get; set; }

        [Input("tags")]
        private InputList<Inputs.LBTCPMonitorTagGetArgs>? _tags;

        /// <summary>
        /// Set of opaque identifiers meaningful to the user
        /// </summary>
        public InputList<Inputs.LBTCPMonitorTagGetArgs> Tags
        {
            get => _tags ?? (_tags = new InputList<Inputs.LBTCPMonitorTagGetArgs>());
            set => _tags = value;
        }

        /// <summary>
        /// Number of seconds the target has to respond to the monitor request
        /// </summary>
        [Input("timeout")]
        public Input<int>? Timeout { get; set; }

        public LBTCPMonitorState()
        {
        }
    }
}
