// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nsxt
{
    public partial class LogicalTier0Router : Pulumi.CustomResource
    {
        /// <summary>
        /// Description of this resource
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The display name of this resource. Defaults to ID if not set
        /// </summary>
        [Output("displayName")]
        public Output<string> DisplayName { get; private set; } = null!;

        /// <summary>
        /// Edge Cluster Id
        /// </summary>
        [Output("edgeClusterId")]
        public Output<string> EdgeClusterId { get; private set; } = null!;

        /// <summary>
        /// Failover mode which determines whether the preferred service router instance for given logical router will preempt the
        /// peer
        /// </summary>
        [Output("failoverMode")]
        public Output<string> FailoverMode { get; private set; } = null!;

        /// <summary>
        /// List of Firewall sections related to the logical router
        /// </summary>
        [Output("firewallSections")]
        public Output<ImmutableArray<Outputs.LogicalTier0RouterFirewallSection>> FirewallSections { get; private set; } = null!;

        /// <summary>
        /// High availability mode
        /// </summary>
        [Output("highAvailabilityMode")]
        public Output<string?> HighAvailabilityMode { get; private set; } = null!;

        /// <summary>
        /// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
        /// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
        /// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
        /// </summary>
        [Output("revision")]
        public Output<int> Revision { get; private set; } = null!;

        /// <summary>
        /// Set of opaque identifiers meaningful to the user
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<Outputs.LogicalTier0RouterTag>> Tags { get; private set; } = null!;


        /// <summary>
        /// Create a LogicalTier0Router resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public LogicalTier0Router(string name, LogicalTier0RouterArgs args, CustomResourceOptions? options = null)
            : base("nsxt:index/logicalTier0Router:LogicalTier0Router", name, args ?? new LogicalTier0RouterArgs(), MakeResourceOptions(options, ""))
        {
        }

        private LogicalTier0Router(string name, Input<string> id, LogicalTier0RouterState? state = null, CustomResourceOptions? options = null)
            : base("nsxt:index/logicalTier0Router:LogicalTier0Router", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing LogicalTier0Router resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static LogicalTier0Router Get(string name, Input<string> id, LogicalTier0RouterState? state = null, CustomResourceOptions? options = null)
        {
            return new LogicalTier0Router(name, id, state, options);
        }
    }

    public sealed class LogicalTier0RouterArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description of this resource
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The display name of this resource. Defaults to ID if not set
        /// </summary>
        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// Edge Cluster Id
        /// </summary>
        [Input("edgeClusterId", required: true)]
        public Input<string> EdgeClusterId { get; set; } = null!;

        /// <summary>
        /// Failover mode which determines whether the preferred service router instance for given logical router will preempt the
        /// peer
        /// </summary>
        [Input("failoverMode")]
        public Input<string>? FailoverMode { get; set; }

        [Input("firewallSections")]
        private InputList<Inputs.LogicalTier0RouterFirewallSectionArgs>? _firewallSections;

        /// <summary>
        /// List of Firewall sections related to the logical router
        /// </summary>
        public InputList<Inputs.LogicalTier0RouterFirewallSectionArgs> FirewallSections
        {
            get => _firewallSections ?? (_firewallSections = new InputList<Inputs.LogicalTier0RouterFirewallSectionArgs>());
            set => _firewallSections = value;
        }

        /// <summary>
        /// High availability mode
        /// </summary>
        [Input("highAvailabilityMode")]
        public Input<string>? HighAvailabilityMode { get; set; }

        [Input("tags")]
        private InputList<Inputs.LogicalTier0RouterTagArgs>? _tags;

        /// <summary>
        /// Set of opaque identifiers meaningful to the user
        /// </summary>
        public InputList<Inputs.LogicalTier0RouterTagArgs> Tags
        {
            get => _tags ?? (_tags = new InputList<Inputs.LogicalTier0RouterTagArgs>());
            set => _tags = value;
        }

        public LogicalTier0RouterArgs()
        {
        }
    }

    public sealed class LogicalTier0RouterState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description of this resource
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The display name of this resource. Defaults to ID if not set
        /// </summary>
        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// Edge Cluster Id
        /// </summary>
        [Input("edgeClusterId")]
        public Input<string>? EdgeClusterId { get; set; }

        /// <summary>
        /// Failover mode which determines whether the preferred service router instance for given logical router will preempt the
        /// peer
        /// </summary>
        [Input("failoverMode")]
        public Input<string>? FailoverMode { get; set; }

        [Input("firewallSections")]
        private InputList<Inputs.LogicalTier0RouterFirewallSectionGetArgs>? _firewallSections;

        /// <summary>
        /// List of Firewall sections related to the logical router
        /// </summary>
        public InputList<Inputs.LogicalTier0RouterFirewallSectionGetArgs> FirewallSections
        {
            get => _firewallSections ?? (_firewallSections = new InputList<Inputs.LogicalTier0RouterFirewallSectionGetArgs>());
            set => _firewallSections = value;
        }

        /// <summary>
        /// High availability mode
        /// </summary>
        [Input("highAvailabilityMode")]
        public Input<string>? HighAvailabilityMode { get; set; }

        /// <summary>
        /// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
        /// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
        /// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
        /// </summary>
        [Input("revision")]
        public Input<int>? Revision { get; set; }

        [Input("tags")]
        private InputList<Inputs.LogicalTier0RouterTagGetArgs>? _tags;

        /// <summary>
        /// Set of opaque identifiers meaningful to the user
        /// </summary>
        public InputList<Inputs.LogicalTier0RouterTagGetArgs> Tags
        {
            get => _tags ?? (_tags = new InputList<Inputs.LogicalTier0RouterTagGetArgs>());
            set => _tags = value;
        }

        public LogicalTier0RouterState()
        {
        }
    }
}
