// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nsxt
{
    public partial class LogicalRouterLinkPortOnTier0 : Pulumi.CustomResource
    {
        /// <summary>
        /// Description of this resource
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The display name of this resource. Defaults to ID if not set
        /// </summary>
        [Output("displayName")]
        public Output<string> DisplayName { get; private set; } = null!;

        /// <summary>
        /// Identifier for port on logical router to connect to
        /// </summary>
        [Output("linkedLogicalRouterPortId")]
        public Output<string> LinkedLogicalRouterPortId { get; private set; } = null!;

        /// <summary>
        /// Identifier for logical router on which this port is created
        /// </summary>
        [Output("logicalRouterId")]
        public Output<string> LogicalRouterId { get; private set; } = null!;

        /// <summary>
        /// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
        /// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
        /// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
        /// </summary>
        [Output("revision")]
        public Output<int> Revision { get; private set; } = null!;

        /// <summary>
        /// Set of opaque identifiers meaningful to the user
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<Outputs.LogicalRouterLinkPortOnTier0Tag>> Tags { get; private set; } = null!;


        /// <summary>
        /// Create a LogicalRouterLinkPortOnTier0 resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public LogicalRouterLinkPortOnTier0(string name, LogicalRouterLinkPortOnTier0Args args, CustomResourceOptions? options = null)
            : base("nsxt:index/logicalRouterLinkPortOnTier0:LogicalRouterLinkPortOnTier0", name, args ?? new LogicalRouterLinkPortOnTier0Args(), MakeResourceOptions(options, ""))
        {
        }

        private LogicalRouterLinkPortOnTier0(string name, Input<string> id, LogicalRouterLinkPortOnTier0State? state = null, CustomResourceOptions? options = null)
            : base("nsxt:index/logicalRouterLinkPortOnTier0:LogicalRouterLinkPortOnTier0", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing LogicalRouterLinkPortOnTier0 resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static LogicalRouterLinkPortOnTier0 Get(string name, Input<string> id, LogicalRouterLinkPortOnTier0State? state = null, CustomResourceOptions? options = null)
        {
            return new LogicalRouterLinkPortOnTier0(name, id, state, options);
        }
    }

    public sealed class LogicalRouterLinkPortOnTier0Args : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description of this resource
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The display name of this resource. Defaults to ID if not set
        /// </summary>
        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// Identifier for logical router on which this port is created
        /// </summary>
        [Input("logicalRouterId", required: true)]
        public Input<string> LogicalRouterId { get; set; } = null!;

        [Input("tags")]
        private InputList<Inputs.LogicalRouterLinkPortOnTier0TagArgs>? _tags;

        /// <summary>
        /// Set of opaque identifiers meaningful to the user
        /// </summary>
        public InputList<Inputs.LogicalRouterLinkPortOnTier0TagArgs> Tags
        {
            get => _tags ?? (_tags = new InputList<Inputs.LogicalRouterLinkPortOnTier0TagArgs>());
            set => _tags = value;
        }

        public LogicalRouterLinkPortOnTier0Args()
        {
        }
    }

    public sealed class LogicalRouterLinkPortOnTier0State : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description of this resource
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The display name of this resource. Defaults to ID if not set
        /// </summary>
        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// Identifier for port on logical router to connect to
        /// </summary>
        [Input("linkedLogicalRouterPortId")]
        public Input<string>? LinkedLogicalRouterPortId { get; set; }

        /// <summary>
        /// Identifier for logical router on which this port is created
        /// </summary>
        [Input("logicalRouterId")]
        public Input<string>? LogicalRouterId { get; set; }

        /// <summary>
        /// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
        /// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
        /// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
        /// </summary>
        [Input("revision")]
        public Input<int>? Revision { get; set; }

        [Input("tags")]
        private InputList<Inputs.LogicalRouterLinkPortOnTier0TagGetArgs>? _tags;

        /// <summary>
        /// Set of opaque identifiers meaningful to the user
        /// </summary>
        public InputList<Inputs.LogicalRouterLinkPortOnTier0TagGetArgs> Tags
        {
            get => _tags ?? (_tags = new InputList<Inputs.LogicalRouterLinkPortOnTier0TagGetArgs>());
            set => _tags = value;
        }

        public LogicalRouterLinkPortOnTier0State()
        {
        }
    }
}
