// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package nsxt

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type DHCPServerProfile struct {
	pulumi.CustomResourceState

	// Description of this resource
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The display name of this resource. Defaults to ID if not set
	DisplayName pulumi.StringOutput `pulumi:"displayName"`
	// Edge cluster uuid
	EdgeClusterId pulumi.StringOutput `pulumi:"edgeClusterId"`
	// Edge nodes from the given cluster
	EdgeClusterMemberIndexes pulumi.IntArrayOutput `pulumi:"edgeClusterMemberIndexes"`
	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
	// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
	// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision pulumi.IntOutput `pulumi:"revision"`
	// Set of opaque identifiers meaningful to the user
	Tags DHCPServerProfileTagArrayOutput `pulumi:"tags"`
}

// NewDHCPServerProfile registers a new resource with the given unique name, arguments, and options.
func NewDHCPServerProfile(ctx *pulumi.Context,
	name string, args *DHCPServerProfileArgs, opts ...pulumi.ResourceOption) (*DHCPServerProfile, error) {
	if args == nil || args.EdgeClusterId == nil {
		return nil, errors.New("missing required argument 'EdgeClusterId'")
	}
	if args == nil {
		args = &DHCPServerProfileArgs{}
	}
	var resource DHCPServerProfile
	err := ctx.RegisterResource("nsxt:index/dHCPServerProfile:DHCPServerProfile", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDHCPServerProfile gets an existing DHCPServerProfile resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDHCPServerProfile(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DHCPServerProfileState, opts ...pulumi.ResourceOption) (*DHCPServerProfile, error) {
	var resource DHCPServerProfile
	err := ctx.ReadResource("nsxt:index/dHCPServerProfile:DHCPServerProfile", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DHCPServerProfile resources.
type dhcpserverProfileState struct {
	// Description of this resource
	Description *string `pulumi:"description"`
	// The display name of this resource. Defaults to ID if not set
	DisplayName *string `pulumi:"displayName"`
	// Edge cluster uuid
	EdgeClusterId *string `pulumi:"edgeClusterId"`
	// Edge nodes from the given cluster
	EdgeClusterMemberIndexes []int `pulumi:"edgeClusterMemberIndexes"`
	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
	// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
	// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision *int `pulumi:"revision"`
	// Set of opaque identifiers meaningful to the user
	Tags []DHCPServerProfileTag `pulumi:"tags"`
}

type DHCPServerProfileState struct {
	// Description of this resource
	Description pulumi.StringPtrInput
	// The display name of this resource. Defaults to ID if not set
	DisplayName pulumi.StringPtrInput
	// Edge cluster uuid
	EdgeClusterId pulumi.StringPtrInput
	// Edge nodes from the given cluster
	EdgeClusterMemberIndexes pulumi.IntArrayInput
	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
	// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
	// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision pulumi.IntPtrInput
	// Set of opaque identifiers meaningful to the user
	Tags DHCPServerProfileTagArrayInput
}

func (DHCPServerProfileState) ElementType() reflect.Type {
	return reflect.TypeOf((*dhcpserverProfileState)(nil)).Elem()
}

type dhcpserverProfileArgs struct {
	// Description of this resource
	Description *string `pulumi:"description"`
	// The display name of this resource. Defaults to ID if not set
	DisplayName *string `pulumi:"displayName"`
	// Edge cluster uuid
	EdgeClusterId string `pulumi:"edgeClusterId"`
	// Edge nodes from the given cluster
	EdgeClusterMemberIndexes []int `pulumi:"edgeClusterMemberIndexes"`
	// Set of opaque identifiers meaningful to the user
	Tags []DHCPServerProfileTag `pulumi:"tags"`
}

// The set of arguments for constructing a DHCPServerProfile resource.
type DHCPServerProfileArgs struct {
	// Description of this resource
	Description pulumi.StringPtrInput
	// The display name of this resource. Defaults to ID if not set
	DisplayName pulumi.StringPtrInput
	// Edge cluster uuid
	EdgeClusterId pulumi.StringInput
	// Edge nodes from the given cluster
	EdgeClusterMemberIndexes pulumi.IntArrayInput
	// Set of opaque identifiers meaningful to the user
	Tags DHCPServerProfileTagArrayInput
}

func (DHCPServerProfileArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dhcpserverProfileArgs)(nil)).Elem()
}
