// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package nsxt

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupLogicalTier1Router(ctx *pulumi.Context, args *LookupLogicalTier1RouterArgs, opts ...pulumi.InvokeOption) (*LookupLogicalTier1RouterResult, error) {
	var rv LookupLogicalTier1RouterResult
	err := ctx.Invoke("nsxt:index/getLogicalTier1Router:getLogicalTier1Router", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getLogicalTier1Router.
type LookupLogicalTier1RouterArgs struct {
	Description   *string `pulumi:"description"`
	DisplayName   *string `pulumi:"displayName"`
	EdgeClusterId *string `pulumi:"edgeClusterId"`
	Id            *string `pulumi:"id"`
}

// A collection of values returned by getLogicalTier1Router.
type LookupLogicalTier1RouterResult struct {
	Description   string `pulumi:"description"`
	DisplayName   string `pulumi:"displayName"`
	EdgeClusterId string `pulumi:"edgeClusterId"`
	Id            string `pulumi:"id"`
}
