// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package nsxt

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func GetPolicyCertificate(ctx *pulumi.Context, args *GetPolicyCertificateArgs, opts ...pulumi.InvokeOption) (*GetPolicyCertificateResult, error) {
	var rv GetPolicyCertificateResult
	err := ctx.Invoke("nsxt:index/getPolicyCertificate:getPolicyCertificate", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPolicyCertificate.
type GetPolicyCertificateArgs struct {
	Description *string `pulumi:"description"`
	DisplayName *string `pulumi:"displayName"`
	Id          *string `pulumi:"id"`
}

// A collection of values returned by getPolicyCertificate.
type GetPolicyCertificateResult struct {
	Description string `pulumi:"description"`
	DisplayName string `pulumi:"displayName"`
	Id          string `pulumi:"id"`
	Path        string `pulumi:"path"`
}
