// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package nsxt

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func GetPolicySegmentSecurityProfile(ctx *pulumi.Context, args *GetPolicySegmentSecurityProfileArgs, opts ...pulumi.InvokeOption) (*GetPolicySegmentSecurityProfileResult, error) {
	var rv GetPolicySegmentSecurityProfileResult
	err := ctx.Invoke("nsxt:index/getPolicySegmentSecurityProfile:getPolicySegmentSecurityProfile", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPolicySegmentSecurityProfile.
type GetPolicySegmentSecurityProfileArgs struct {
	Description *string `pulumi:"description"`
	DisplayName *string `pulumi:"displayName"`
	Id          *string `pulumi:"id"`
}

// A collection of values returned by getPolicySegmentSecurityProfile.
type GetPolicySegmentSecurityProfileResult struct {
	Description string `pulumi:"description"`
	DisplayName string `pulumi:"displayName"`
	Id          string `pulumi:"id"`
	Path        string `pulumi:"path"`
}
