// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package nsxt

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupPolicyGroup(ctx *pulumi.Context, args *LookupPolicyGroupArgs, opts ...pulumi.InvokeOption) (*LookupPolicyGroupResult, error) {
	var rv LookupPolicyGroupResult
	err := ctx.Invoke("nsxt:index/getPolicyGroup:getPolicyGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPolicyGroup.
type LookupPolicyGroupArgs struct {
	Description *string `pulumi:"description"`
	DisplayName *string `pulumi:"displayName"`
	Domain      *string `pulumi:"domain"`
	Id          *string `pulumi:"id"`
}

// A collection of values returned by getPolicyGroup.
type LookupPolicyGroupResult struct {
	Description string  `pulumi:"description"`
	DisplayName string  `pulumi:"displayName"`
	Domain      *string `pulumi:"domain"`
	Id          string  `pulumi:"id"`
	Path        string  `pulumi:"path"`
}
