// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package nsxt

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func GetPolicyIPDiscoveryProfile(ctx *pulumi.Context, args *GetPolicyIPDiscoveryProfileArgs, opts ...pulumi.InvokeOption) (*GetPolicyIPDiscoveryProfileResult, error) {
	var rv GetPolicyIPDiscoveryProfileResult
	err := ctx.Invoke("nsxt:index/getPolicyIPDiscoveryProfile:getPolicyIPDiscoveryProfile", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPolicyIPDiscoveryProfile.
type GetPolicyIPDiscoveryProfileArgs struct {
	Description *string `pulumi:"description"`
	DisplayName *string `pulumi:"displayName"`
	Id          *string `pulumi:"id"`
}

// A collection of values returned by getPolicyIPDiscoveryProfile.
type GetPolicyIPDiscoveryProfileResult struct {
	Description string `pulumi:"description"`
	DisplayName string `pulumi:"displayName"`
	Id          string `pulumi:"id"`
	Path        string `pulumi:"path"`
}
