// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package nsxt

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type LBUDPMonitor struct {
	pulumi.CustomResourceState

	// Description of this resource
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The display name of this resource. Defaults to ID if not set
	DisplayName pulumi.StringOutput `pulumi:"displayName"`
	// Number of consecutive checks that must fail before marking it down
	FallCount pulumi.IntPtrOutput `pulumi:"fallCount"`
	// The frequency at which the system issues the monitor check (in seconds)
	Interval pulumi.IntPtrOutput `pulumi:"interval"`
	// If the monitor port is specified, it would override pool member port setting for healthcheck. A port range is not
	// supported
	MonitorPort pulumi.StringPtrOutput `pulumi:"monitorPort"`
	// Expected data, if specified, can be anywhere in the response and it has to be a string, regular expressions are not
	// supported
	Receive pulumi.StringOutput `pulumi:"receive"`
	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
	// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
	// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision pulumi.IntOutput `pulumi:"revision"`
	// Number of consecutive checks that must pass before marking it up
	RiseCount pulumi.IntPtrOutput `pulumi:"riseCount"`
	// The data to be sent to the monitored server.
	Send pulumi.StringOutput `pulumi:"send"`
	// Set of opaque identifiers meaningful to the user
	Tags LBUDPMonitorTagArrayOutput `pulumi:"tags"`
	// Number of seconds the target has to respond to the monitor request
	Timeout pulumi.IntPtrOutput `pulumi:"timeout"`
}

// NewLBUDPMonitor registers a new resource with the given unique name, arguments, and options.
func NewLBUDPMonitor(ctx *pulumi.Context,
	name string, args *LBUDPMonitorArgs, opts ...pulumi.ResourceOption) (*LBUDPMonitor, error) {
	if args == nil || args.Receive == nil {
		return nil, errors.New("missing required argument 'Receive'")
	}
	if args == nil || args.Send == nil {
		return nil, errors.New("missing required argument 'Send'")
	}
	if args == nil {
		args = &LBUDPMonitorArgs{}
	}
	var resource LBUDPMonitor
	err := ctx.RegisterResource("nsxt:index/lBUDPMonitor:LBUDPMonitor", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLBUDPMonitor gets an existing LBUDPMonitor resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLBUDPMonitor(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LBUDPMonitorState, opts ...pulumi.ResourceOption) (*LBUDPMonitor, error) {
	var resource LBUDPMonitor
	err := ctx.ReadResource("nsxt:index/lBUDPMonitor:LBUDPMonitor", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LBUDPMonitor resources.
type lbudpmonitorState struct {
	// Description of this resource
	Description *string `pulumi:"description"`
	// The display name of this resource. Defaults to ID if not set
	DisplayName *string `pulumi:"displayName"`
	// Number of consecutive checks that must fail before marking it down
	FallCount *int `pulumi:"fallCount"`
	// The frequency at which the system issues the monitor check (in seconds)
	Interval *int `pulumi:"interval"`
	// If the monitor port is specified, it would override pool member port setting for healthcheck. A port range is not
	// supported
	MonitorPort *string `pulumi:"monitorPort"`
	// Expected data, if specified, can be anywhere in the response and it has to be a string, regular expressions are not
	// supported
	Receive *string `pulumi:"receive"`
	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
	// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
	// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision *int `pulumi:"revision"`
	// Number of consecutive checks that must pass before marking it up
	RiseCount *int `pulumi:"riseCount"`
	// The data to be sent to the monitored server.
	Send *string `pulumi:"send"`
	// Set of opaque identifiers meaningful to the user
	Tags []LBUDPMonitorTag `pulumi:"tags"`
	// Number of seconds the target has to respond to the monitor request
	Timeout *int `pulumi:"timeout"`
}

type LBUDPMonitorState struct {
	// Description of this resource
	Description pulumi.StringPtrInput
	// The display name of this resource. Defaults to ID if not set
	DisplayName pulumi.StringPtrInput
	// Number of consecutive checks that must fail before marking it down
	FallCount pulumi.IntPtrInput
	// The frequency at which the system issues the monitor check (in seconds)
	Interval pulumi.IntPtrInput
	// If the monitor port is specified, it would override pool member port setting for healthcheck. A port range is not
	// supported
	MonitorPort pulumi.StringPtrInput
	// Expected data, if specified, can be anywhere in the response and it has to be a string, regular expressions are not
	// supported
	Receive pulumi.StringPtrInput
	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
	// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
	// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision pulumi.IntPtrInput
	// Number of consecutive checks that must pass before marking it up
	RiseCount pulumi.IntPtrInput
	// The data to be sent to the monitored server.
	Send pulumi.StringPtrInput
	// Set of opaque identifiers meaningful to the user
	Tags LBUDPMonitorTagArrayInput
	// Number of seconds the target has to respond to the monitor request
	Timeout pulumi.IntPtrInput
}

func (LBUDPMonitorState) ElementType() reflect.Type {
	return reflect.TypeOf((*lbudpmonitorState)(nil)).Elem()
}

type lbudpmonitorArgs struct {
	// Description of this resource
	Description *string `pulumi:"description"`
	// The display name of this resource. Defaults to ID if not set
	DisplayName *string `pulumi:"displayName"`
	// Number of consecutive checks that must fail before marking it down
	FallCount *int `pulumi:"fallCount"`
	// The frequency at which the system issues the monitor check (in seconds)
	Interval *int `pulumi:"interval"`
	// If the monitor port is specified, it would override pool member port setting for healthcheck. A port range is not
	// supported
	MonitorPort *string `pulumi:"monitorPort"`
	// Expected data, if specified, can be anywhere in the response and it has to be a string, regular expressions are not
	// supported
	Receive string `pulumi:"receive"`
	// Number of consecutive checks that must pass before marking it up
	RiseCount *int `pulumi:"riseCount"`
	// The data to be sent to the monitored server.
	Send string `pulumi:"send"`
	// Set of opaque identifiers meaningful to the user
	Tags []LBUDPMonitorTag `pulumi:"tags"`
	// Number of seconds the target has to respond to the monitor request
	Timeout *int `pulumi:"timeout"`
}

// The set of arguments for constructing a LBUDPMonitor resource.
type LBUDPMonitorArgs struct {
	// Description of this resource
	Description pulumi.StringPtrInput
	// The display name of this resource. Defaults to ID if not set
	DisplayName pulumi.StringPtrInput
	// Number of consecutive checks that must fail before marking it down
	FallCount pulumi.IntPtrInput
	// The frequency at which the system issues the monitor check (in seconds)
	Interval pulumi.IntPtrInput
	// If the monitor port is specified, it would override pool member port setting for healthcheck. A port range is not
	// supported
	MonitorPort pulumi.StringPtrInput
	// Expected data, if specified, can be anywhere in the response and it has to be a string, regular expressions are not
	// supported
	Receive pulumi.StringInput
	// Number of consecutive checks that must pass before marking it up
	RiseCount pulumi.IntPtrInput
	// The data to be sent to the monitored server.
	Send pulumi.StringInput
	// Set of opaque identifiers meaningful to the user
	Tags LBUDPMonitorTagArrayInput
	// Number of seconds the target has to respond to the monitor request
	Timeout pulumi.IntPtrInput
}

func (LBUDPMonitorArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*lbudpmonitorArgs)(nil)).Elem()
}
