// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package nsxt

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type LogicalRouterLinkPortOnTier1 struct {
	pulumi.CustomResourceState

	// Description of this resource
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The display name of this resource. Defaults to ID if not set
	DisplayName pulumi.StringOutput `pulumi:"displayName"`
	// Identifier for port on logical router to connect to
	LinkedLogicalRouterPortId pulumi.StringOutput `pulumi:"linkedLogicalRouterPortId"`
	// Identifier for logical router on which this port is created
	LogicalRouterId pulumi.StringOutput `pulumi:"logicalRouterId"`
	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
	// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
	// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision pulumi.IntOutput `pulumi:"revision"`
	// Set of opaque identifiers meaningful to the user
	Tags LogicalRouterLinkPortOnTier1TagArrayOutput `pulumi:"tags"`
}

// NewLogicalRouterLinkPortOnTier1 registers a new resource with the given unique name, arguments, and options.
func NewLogicalRouterLinkPortOnTier1(ctx *pulumi.Context,
	name string, args *LogicalRouterLinkPortOnTier1Args, opts ...pulumi.ResourceOption) (*LogicalRouterLinkPortOnTier1, error) {
	if args == nil || args.LinkedLogicalRouterPortId == nil {
		return nil, errors.New("missing required argument 'LinkedLogicalRouterPortId'")
	}
	if args == nil || args.LogicalRouterId == nil {
		return nil, errors.New("missing required argument 'LogicalRouterId'")
	}
	if args == nil {
		args = &LogicalRouterLinkPortOnTier1Args{}
	}
	var resource LogicalRouterLinkPortOnTier1
	err := ctx.RegisterResource("nsxt:index/logicalRouterLinkPortOnTier1:LogicalRouterLinkPortOnTier1", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLogicalRouterLinkPortOnTier1 gets an existing LogicalRouterLinkPortOnTier1 resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLogicalRouterLinkPortOnTier1(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LogicalRouterLinkPortOnTier1State, opts ...pulumi.ResourceOption) (*LogicalRouterLinkPortOnTier1, error) {
	var resource LogicalRouterLinkPortOnTier1
	err := ctx.ReadResource("nsxt:index/logicalRouterLinkPortOnTier1:LogicalRouterLinkPortOnTier1", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LogicalRouterLinkPortOnTier1 resources.
type logicalRouterLinkPortOnTier1State struct {
	// Description of this resource
	Description *string `pulumi:"description"`
	// The display name of this resource. Defaults to ID if not set
	DisplayName *string `pulumi:"displayName"`
	// Identifier for port on logical router to connect to
	LinkedLogicalRouterPortId *string `pulumi:"linkedLogicalRouterPortId"`
	// Identifier for logical router on which this port is created
	LogicalRouterId *string `pulumi:"logicalRouterId"`
	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
	// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
	// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision *int `pulumi:"revision"`
	// Set of opaque identifiers meaningful to the user
	Tags []LogicalRouterLinkPortOnTier1Tag `pulumi:"tags"`
}

type LogicalRouterLinkPortOnTier1State struct {
	// Description of this resource
	Description pulumi.StringPtrInput
	// The display name of this resource. Defaults to ID if not set
	DisplayName pulumi.StringPtrInput
	// Identifier for port on logical router to connect to
	LinkedLogicalRouterPortId pulumi.StringPtrInput
	// Identifier for logical router on which this port is created
	LogicalRouterId pulumi.StringPtrInput
	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
	// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
	// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision pulumi.IntPtrInput
	// Set of opaque identifiers meaningful to the user
	Tags LogicalRouterLinkPortOnTier1TagArrayInput
}

func (LogicalRouterLinkPortOnTier1State) ElementType() reflect.Type {
	return reflect.TypeOf((*logicalRouterLinkPortOnTier1State)(nil)).Elem()
}

type logicalRouterLinkPortOnTier1Args struct {
	// Description of this resource
	Description *string `pulumi:"description"`
	// The display name of this resource. Defaults to ID if not set
	DisplayName *string `pulumi:"displayName"`
	// Identifier for port on logical router to connect to
	LinkedLogicalRouterPortId string `pulumi:"linkedLogicalRouterPortId"`
	// Identifier for logical router on which this port is created
	LogicalRouterId string `pulumi:"logicalRouterId"`
	// Set of opaque identifiers meaningful to the user
	Tags []LogicalRouterLinkPortOnTier1Tag `pulumi:"tags"`
}

// The set of arguments for constructing a LogicalRouterLinkPortOnTier1 resource.
type LogicalRouterLinkPortOnTier1Args struct {
	// Description of this resource
	Description pulumi.StringPtrInput
	// The display name of this resource. Defaults to ID if not set
	DisplayName pulumi.StringPtrInput
	// Identifier for port on logical router to connect to
	LinkedLogicalRouterPortId pulumi.StringInput
	// Identifier for logical router on which this port is created
	LogicalRouterId pulumi.StringInput
	// Set of opaque identifiers meaningful to the user
	Tags LogicalRouterLinkPortOnTier1TagArrayInput
}

func (LogicalRouterLinkPortOnTier1Args) ElementType() reflect.Type {
	return reflect.TypeOf((*logicalRouterLinkPortOnTier1Args)(nil)).Elem()
}
