// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package nsxt

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type LogicalDHCPPort struct {
	pulumi.CustomResourceState

	// Represents Desired state of the object
	AdminState pulumi.StringPtrOutput `pulumi:"adminState"`
	// Description of this resource
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Id of the Logical DHCP server this port belongs to
	DhcpServerId pulumi.StringOutput `pulumi:"dhcpServerId"`
	// The display name of this resource. Defaults to ID if not set
	DisplayName pulumi.StringOutput `pulumi:"displayName"`
	// Id of the Logical switch that this port belongs to
	LogicalSwitchId pulumi.StringOutput `pulumi:"logicalSwitchId"`
	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
	// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
	// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision pulumi.IntOutput `pulumi:"revision"`
	// Set of opaque identifiers meaningful to the user
	Tags LogicalDHCPPortTagArrayOutput `pulumi:"tags"`
}

// NewLogicalDHCPPort registers a new resource with the given unique name, arguments, and options.
func NewLogicalDHCPPort(ctx *pulumi.Context,
	name string, args *LogicalDHCPPortArgs, opts ...pulumi.ResourceOption) (*LogicalDHCPPort, error) {
	if args == nil || args.DhcpServerId == nil {
		return nil, errors.New("missing required argument 'DhcpServerId'")
	}
	if args == nil || args.LogicalSwitchId == nil {
		return nil, errors.New("missing required argument 'LogicalSwitchId'")
	}
	if args == nil {
		args = &LogicalDHCPPortArgs{}
	}
	var resource LogicalDHCPPort
	err := ctx.RegisterResource("nsxt:index/logicalDHCPPort:LogicalDHCPPort", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLogicalDHCPPort gets an existing LogicalDHCPPort resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLogicalDHCPPort(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LogicalDHCPPortState, opts ...pulumi.ResourceOption) (*LogicalDHCPPort, error) {
	var resource LogicalDHCPPort
	err := ctx.ReadResource("nsxt:index/logicalDHCPPort:LogicalDHCPPort", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LogicalDHCPPort resources.
type logicalDHCPPortState struct {
	// Represents Desired state of the object
	AdminState *string `pulumi:"adminState"`
	// Description of this resource
	Description *string `pulumi:"description"`
	// Id of the Logical DHCP server this port belongs to
	DhcpServerId *string `pulumi:"dhcpServerId"`
	// The display name of this resource. Defaults to ID if not set
	DisplayName *string `pulumi:"displayName"`
	// Id of the Logical switch that this port belongs to
	LogicalSwitchId *string `pulumi:"logicalSwitchId"`
	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
	// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
	// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision *int `pulumi:"revision"`
	// Set of opaque identifiers meaningful to the user
	Tags []LogicalDHCPPortTag `pulumi:"tags"`
}

type LogicalDHCPPortState struct {
	// Represents Desired state of the object
	AdminState pulumi.StringPtrInput
	// Description of this resource
	Description pulumi.StringPtrInput
	// Id of the Logical DHCP server this port belongs to
	DhcpServerId pulumi.StringPtrInput
	// The display name of this resource. Defaults to ID if not set
	DisplayName pulumi.StringPtrInput
	// Id of the Logical switch that this port belongs to
	LogicalSwitchId pulumi.StringPtrInput
	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
	// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
	// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision pulumi.IntPtrInput
	// Set of opaque identifiers meaningful to the user
	Tags LogicalDHCPPortTagArrayInput
}

func (LogicalDHCPPortState) ElementType() reflect.Type {
	return reflect.TypeOf((*logicalDHCPPortState)(nil)).Elem()
}

type logicalDHCPPortArgs struct {
	// Represents Desired state of the object
	AdminState *string `pulumi:"adminState"`
	// Description of this resource
	Description *string `pulumi:"description"`
	// Id of the Logical DHCP server this port belongs to
	DhcpServerId string `pulumi:"dhcpServerId"`
	// The display name of this resource. Defaults to ID if not set
	DisplayName *string `pulumi:"displayName"`
	// Id of the Logical switch that this port belongs to
	LogicalSwitchId string `pulumi:"logicalSwitchId"`
	// Set of opaque identifiers meaningful to the user
	Tags []LogicalDHCPPortTag `pulumi:"tags"`
}

// The set of arguments for constructing a LogicalDHCPPort resource.
type LogicalDHCPPortArgs struct {
	// Represents Desired state of the object
	AdminState pulumi.StringPtrInput
	// Description of this resource
	Description pulumi.StringPtrInput
	// Id of the Logical DHCP server this port belongs to
	DhcpServerId pulumi.StringInput
	// The display name of this resource. Defaults to ID if not set
	DisplayName pulumi.StringPtrInput
	// Id of the Logical switch that this port belongs to
	LogicalSwitchId pulumi.StringInput
	// Set of opaque identifiers meaningful to the user
	Tags LogicalDHCPPortTagArrayInput
}

func (LogicalDHCPPortArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*logicalDHCPPortArgs)(nil)).Elem()
}
