// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package nsxt

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type NATRule struct {
	pulumi.CustomResourceState

	// The action for the NAT Rule
	Action pulumi.StringOutput `pulumi:"action"`
	// Description of this resource
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The display name of this resource. Defaults to ID if not set
	DisplayName pulumi.StringOutput `pulumi:"displayName"`
	// enable/disable the rule
	Enabled pulumi.BoolPtrOutput `pulumi:"enabled"`
	// enable/disable the logging of rule
	Logging pulumi.BoolPtrOutput `pulumi:"logging"`
	// Logical router id
	LogicalRouterId pulumi.StringOutput `pulumi:"logicalRouterId"`
	// IP Address | CIDR
	MatchDestinationNetwork pulumi.StringPtrOutput `pulumi:"matchDestinationNetwork"`
	// IP Address | CIDR
	MatchSourceNetwork pulumi.StringPtrOutput `pulumi:"matchSourceNetwork"`
	// A boolean flag which reflects whether the following firewall stage will be skipped
	NatPass pulumi.BoolPtrOutput `pulumi:"natPass"`
	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
	// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
	// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision pulumi.IntOutput `pulumi:"revision"`
	// The priority of the rule (ascending). Valid range [0-2147483647]
	RulePriority pulumi.IntOutput `pulumi:"rulePriority"`
	// Set of opaque identifiers meaningful to the user
	Tags NATRuleTagArrayOutput `pulumi:"tags"`
	// IP Address | IP Range | CIDR
	TranslatedNetwork pulumi.StringPtrOutput `pulumi:"translatedNetwork"`
	// port number or port range. DNAT only
	TranslatedPorts pulumi.StringPtrOutput `pulumi:"translatedPorts"`
}

// NewNATRule registers a new resource with the given unique name, arguments, and options.
func NewNATRule(ctx *pulumi.Context,
	name string, args *NATRuleArgs, opts ...pulumi.ResourceOption) (*NATRule, error) {
	if args == nil || args.Action == nil {
		return nil, errors.New("missing required argument 'Action'")
	}
	if args == nil || args.LogicalRouterId == nil {
		return nil, errors.New("missing required argument 'LogicalRouterId'")
	}
	if args == nil {
		args = &NATRuleArgs{}
	}
	var resource NATRule
	err := ctx.RegisterResource("nsxt:index/nATRule:NATRule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNATRule gets an existing NATRule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNATRule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NATRuleState, opts ...pulumi.ResourceOption) (*NATRule, error) {
	var resource NATRule
	err := ctx.ReadResource("nsxt:index/nATRule:NATRule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NATRule resources.
type natruleState struct {
	// The action for the NAT Rule
	Action *string `pulumi:"action"`
	// Description of this resource
	Description *string `pulumi:"description"`
	// The display name of this resource. Defaults to ID if not set
	DisplayName *string `pulumi:"displayName"`
	// enable/disable the rule
	Enabled *bool `pulumi:"enabled"`
	// enable/disable the logging of rule
	Logging *bool `pulumi:"logging"`
	// Logical router id
	LogicalRouterId *string `pulumi:"logicalRouterId"`
	// IP Address | CIDR
	MatchDestinationNetwork *string `pulumi:"matchDestinationNetwork"`
	// IP Address | CIDR
	MatchSourceNetwork *string `pulumi:"matchSourceNetwork"`
	// A boolean flag which reflects whether the following firewall stage will be skipped
	NatPass *bool `pulumi:"natPass"`
	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
	// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
	// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision *int `pulumi:"revision"`
	// The priority of the rule (ascending). Valid range [0-2147483647]
	RulePriority *int `pulumi:"rulePriority"`
	// Set of opaque identifiers meaningful to the user
	Tags []NATRuleTag `pulumi:"tags"`
	// IP Address | IP Range | CIDR
	TranslatedNetwork *string `pulumi:"translatedNetwork"`
	// port number or port range. DNAT only
	TranslatedPorts *string `pulumi:"translatedPorts"`
}

type NATRuleState struct {
	// The action for the NAT Rule
	Action pulumi.StringPtrInput
	// Description of this resource
	Description pulumi.StringPtrInput
	// The display name of this resource. Defaults to ID if not set
	DisplayName pulumi.StringPtrInput
	// enable/disable the rule
	Enabled pulumi.BoolPtrInput
	// enable/disable the logging of rule
	Logging pulumi.BoolPtrInput
	// Logical router id
	LogicalRouterId pulumi.StringPtrInput
	// IP Address | CIDR
	MatchDestinationNetwork pulumi.StringPtrInput
	// IP Address | CIDR
	MatchSourceNetwork pulumi.StringPtrInput
	// A boolean flag which reflects whether the following firewall stage will be skipped
	NatPass pulumi.BoolPtrInput
	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
	// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
	// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision pulumi.IntPtrInput
	// The priority of the rule (ascending). Valid range [0-2147483647]
	RulePriority pulumi.IntPtrInput
	// Set of opaque identifiers meaningful to the user
	Tags NATRuleTagArrayInput
	// IP Address | IP Range | CIDR
	TranslatedNetwork pulumi.StringPtrInput
	// port number or port range. DNAT only
	TranslatedPorts pulumi.StringPtrInput
}

func (NATRuleState) ElementType() reflect.Type {
	return reflect.TypeOf((*natruleState)(nil)).Elem()
}

type natruleArgs struct {
	// The action for the NAT Rule
	Action string `pulumi:"action"`
	// Description of this resource
	Description *string `pulumi:"description"`
	// The display name of this resource. Defaults to ID if not set
	DisplayName *string `pulumi:"displayName"`
	// enable/disable the rule
	Enabled *bool `pulumi:"enabled"`
	// enable/disable the logging of rule
	Logging *bool `pulumi:"logging"`
	// Logical router id
	LogicalRouterId string `pulumi:"logicalRouterId"`
	// IP Address | CIDR
	MatchDestinationNetwork *string `pulumi:"matchDestinationNetwork"`
	// IP Address | CIDR
	MatchSourceNetwork *string `pulumi:"matchSourceNetwork"`
	// A boolean flag which reflects whether the following firewall stage will be skipped
	NatPass *bool `pulumi:"natPass"`
	// The priority of the rule (ascending). Valid range [0-2147483647]
	RulePriority *int `pulumi:"rulePriority"`
	// Set of opaque identifiers meaningful to the user
	Tags []NATRuleTag `pulumi:"tags"`
	// IP Address | IP Range | CIDR
	TranslatedNetwork *string `pulumi:"translatedNetwork"`
	// port number or port range. DNAT only
	TranslatedPorts *string `pulumi:"translatedPorts"`
}

// The set of arguments for constructing a NATRule resource.
type NATRuleArgs struct {
	// The action for the NAT Rule
	Action pulumi.StringInput
	// Description of this resource
	Description pulumi.StringPtrInput
	// The display name of this resource. Defaults to ID if not set
	DisplayName pulumi.StringPtrInput
	// enable/disable the rule
	Enabled pulumi.BoolPtrInput
	// enable/disable the logging of rule
	Logging pulumi.BoolPtrInput
	// Logical router id
	LogicalRouterId pulumi.StringInput
	// IP Address | CIDR
	MatchDestinationNetwork pulumi.StringPtrInput
	// IP Address | CIDR
	MatchSourceNetwork pulumi.StringPtrInput
	// A boolean flag which reflects whether the following firewall stage will be skipped
	NatPass pulumi.BoolPtrInput
	// The priority of the rule (ascending). Valid range [0-2147483647]
	RulePriority pulumi.IntPtrInput
	// Set of opaque identifiers meaningful to the user
	Tags NATRuleTagArrayInput
	// IP Address | IP Range | CIDR
	TranslatedNetwork pulumi.StringPtrInput
	// port number or port range. DNAT only
	TranslatedPorts pulumi.StringPtrInput
}

func (NATRuleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*natruleArgs)(nil)).Elem()
}
