// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package nsxt

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type PolicyLBPool struct {
	pulumi.CustomResourceState

	// Active healthcheck is disabled by default and can be enabled using this setting
	ActiveMonitorPath pulumi.StringPtrOutput `pulumi:"activeMonitorPath"`
	Algorithm         pulumi.StringPtrOutput `pulumi:"algorithm"`
	// Description for this resource
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Display name for this resource
	DisplayName pulumi.StringOutput `pulumi:"displayName"`
	// Dynamic pool members for the loadbalancing pool. When member group is defined, members setting should not be specified
	MemberGroup PolicyLBPoolMemberGroupPtrOutput `pulumi:"memberGroup"`
	// List of server pool members. Each pool member is identified, typically, by an IP address and a port
	Members          PolicyLBPoolMemberArrayOutput `pulumi:"members"`
	MinActiveMembers pulumi.IntPtrOutput           `pulumi:"minActiveMembers"`
	// NSX ID for this resource
	NsxId pulumi.StringOutput `pulumi:"nsxId"`
	// Policy path for passive health monitor
	PassiveMonitorPath pulumi.StringPtrOutput `pulumi:"passiveMonitorPath"`
	// Policy path for this resource
	Path pulumi.StringOutput `pulumi:"path"`
	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
	// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
	// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision pulumi.IntOutput `pulumi:"revision"`
	// SNAT configuration
	Snat PolicyLBPoolSnatOutput `pulumi:"snat"`
	// Set of opaque identifiers meaningful to the user
	Tags                   PolicyLBPoolTagArrayOutput `pulumi:"tags"`
	TcpMultiplexingEnabled pulumi.BoolPtrOutput       `pulumi:"tcpMultiplexingEnabled"`
	TcpMultiplexingNumber  pulumi.IntPtrOutput        `pulumi:"tcpMultiplexingNumber"`
}

// NewPolicyLBPool registers a new resource with the given unique name, arguments, and options.
func NewPolicyLBPool(ctx *pulumi.Context,
	name string, args *PolicyLBPoolArgs, opts ...pulumi.ResourceOption) (*PolicyLBPool, error) {
	if args == nil || args.DisplayName == nil {
		return nil, errors.New("missing required argument 'DisplayName'")
	}
	if args == nil {
		args = &PolicyLBPoolArgs{}
	}
	var resource PolicyLBPool
	err := ctx.RegisterResource("nsxt:index/policyLBPool:PolicyLBPool", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPolicyLBPool gets an existing PolicyLBPool resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPolicyLBPool(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PolicyLBPoolState, opts ...pulumi.ResourceOption) (*PolicyLBPool, error) {
	var resource PolicyLBPool
	err := ctx.ReadResource("nsxt:index/policyLBPool:PolicyLBPool", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PolicyLBPool resources.
type policyLBPoolState struct {
	// Active healthcheck is disabled by default and can be enabled using this setting
	ActiveMonitorPath *string `pulumi:"activeMonitorPath"`
	Algorithm         *string `pulumi:"algorithm"`
	// Description for this resource
	Description *string `pulumi:"description"`
	// Display name for this resource
	DisplayName *string `pulumi:"displayName"`
	// Dynamic pool members for the loadbalancing pool. When member group is defined, members setting should not be specified
	MemberGroup *PolicyLBPoolMemberGroup `pulumi:"memberGroup"`
	// List of server pool members. Each pool member is identified, typically, by an IP address and a port
	Members          []PolicyLBPoolMember `pulumi:"members"`
	MinActiveMembers *int                 `pulumi:"minActiveMembers"`
	// NSX ID for this resource
	NsxId *string `pulumi:"nsxId"`
	// Policy path for passive health monitor
	PassiveMonitorPath *string `pulumi:"passiveMonitorPath"`
	// Policy path for this resource
	Path *string `pulumi:"path"`
	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
	// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
	// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision *int `pulumi:"revision"`
	// SNAT configuration
	Snat *PolicyLBPoolSnat `pulumi:"snat"`
	// Set of opaque identifiers meaningful to the user
	Tags                   []PolicyLBPoolTag `pulumi:"tags"`
	TcpMultiplexingEnabled *bool             `pulumi:"tcpMultiplexingEnabled"`
	TcpMultiplexingNumber  *int              `pulumi:"tcpMultiplexingNumber"`
}

type PolicyLBPoolState struct {
	// Active healthcheck is disabled by default and can be enabled using this setting
	ActiveMonitorPath pulumi.StringPtrInput
	Algorithm         pulumi.StringPtrInput
	// Description for this resource
	Description pulumi.StringPtrInput
	// Display name for this resource
	DisplayName pulumi.StringPtrInput
	// Dynamic pool members for the loadbalancing pool. When member group is defined, members setting should not be specified
	MemberGroup PolicyLBPoolMemberGroupPtrInput
	// List of server pool members. Each pool member is identified, typically, by an IP address and a port
	Members          PolicyLBPoolMemberArrayInput
	MinActiveMembers pulumi.IntPtrInput
	// NSX ID for this resource
	NsxId pulumi.StringPtrInput
	// Policy path for passive health monitor
	PassiveMonitorPath pulumi.StringPtrInput
	// Policy path for this resource
	Path pulumi.StringPtrInput
	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
	// changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
	// operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision pulumi.IntPtrInput
	// SNAT configuration
	Snat PolicyLBPoolSnatPtrInput
	// Set of opaque identifiers meaningful to the user
	Tags                   PolicyLBPoolTagArrayInput
	TcpMultiplexingEnabled pulumi.BoolPtrInput
	TcpMultiplexingNumber  pulumi.IntPtrInput
}

func (PolicyLBPoolState) ElementType() reflect.Type {
	return reflect.TypeOf((*policyLBPoolState)(nil)).Elem()
}

type policyLBPoolArgs struct {
	// Active healthcheck is disabled by default and can be enabled using this setting
	ActiveMonitorPath *string `pulumi:"activeMonitorPath"`
	Algorithm         *string `pulumi:"algorithm"`
	// Description for this resource
	Description *string `pulumi:"description"`
	// Display name for this resource
	DisplayName string `pulumi:"displayName"`
	// Dynamic pool members for the loadbalancing pool. When member group is defined, members setting should not be specified
	MemberGroup *PolicyLBPoolMemberGroup `pulumi:"memberGroup"`
	// List of server pool members. Each pool member is identified, typically, by an IP address and a port
	Members          []PolicyLBPoolMember `pulumi:"members"`
	MinActiveMembers *int                 `pulumi:"minActiveMembers"`
	// NSX ID for this resource
	NsxId *string `pulumi:"nsxId"`
	// Policy path for passive health monitor
	PassiveMonitorPath *string `pulumi:"passiveMonitorPath"`
	// SNAT configuration
	Snat *PolicyLBPoolSnat `pulumi:"snat"`
	// Set of opaque identifiers meaningful to the user
	Tags                   []PolicyLBPoolTag `pulumi:"tags"`
	TcpMultiplexingEnabled *bool             `pulumi:"tcpMultiplexingEnabled"`
	TcpMultiplexingNumber  *int              `pulumi:"tcpMultiplexingNumber"`
}

// The set of arguments for constructing a PolicyLBPool resource.
type PolicyLBPoolArgs struct {
	// Active healthcheck is disabled by default and can be enabled using this setting
	ActiveMonitorPath pulumi.StringPtrInput
	Algorithm         pulumi.StringPtrInput
	// Description for this resource
	Description pulumi.StringPtrInput
	// Display name for this resource
	DisplayName pulumi.StringInput
	// Dynamic pool members for the loadbalancing pool. When member group is defined, members setting should not be specified
	MemberGroup PolicyLBPoolMemberGroupPtrInput
	// List of server pool members. Each pool member is identified, typically, by an IP address and a port
	Members          PolicyLBPoolMemberArrayInput
	MinActiveMembers pulumi.IntPtrInput
	// NSX ID for this resource
	NsxId pulumi.StringPtrInput
	// Policy path for passive health monitor
	PassiveMonitorPath pulumi.StringPtrInput
	// SNAT configuration
	Snat PolicyLBPoolSnatPtrInput
	// Set of opaque identifiers meaningful to the user
	Tags                   PolicyLBPoolTagArrayInput
	TcpMultiplexingEnabled pulumi.BoolPtrInput
	TcpMultiplexingNumber  pulumi.IntPtrInput
}

func (PolicyLBPoolArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*policyLBPoolArgs)(nil)).Elem()
}
