// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nsxt.Outputs
{

    [OutputType]
    public sealed class NSroupMembershipCriteria
    {
        public readonly string? Scope;
        public readonly string? ScopeOp;
        public readonly string? Tag;
        public readonly string? TagOp;
        public readonly string TargetType;

        [OutputConstructor]
        private NSroupMembershipCriteria(
            string? scope,

            string? scopeOp,

            string? tag,

            string? tagOp,

            string targetType)
        {
            Scope = scope;
            ScopeOp = scopeOp;
            Tag = tag;
            TagOp = tagOp;
            TargetType = targetType;
        }
    }
}
