// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nsxt.Outputs
{

    [OutputType]
    public sealed class PolicyGroupCriteria
    {
        public readonly ImmutableArray<Outputs.PolicyGroupCriteriaCondition> Conditions;
        public readonly Outputs.PolicyGroupCriteriaIpaddressExpression? IpaddressExpression;
        public readonly Outputs.PolicyGroupCriteriaMacaddressExpression? MacaddressExpression;
        public readonly Outputs.PolicyGroupCriteriaPathExpression? PathExpression;

        [OutputConstructor]
        private PolicyGroupCriteria(
            ImmutableArray<Outputs.PolicyGroupCriteriaCondition> conditions,

            Outputs.PolicyGroupCriteriaIpaddressExpression? ipaddressExpression,

            Outputs.PolicyGroupCriteriaMacaddressExpression? macaddressExpression,

            Outputs.PolicyGroupCriteriaPathExpression? pathExpression)
        {
            Conditions = conditions;
            IpaddressExpression = ipaddressExpression;
            MacaddressExpression = macaddressExpression;
            PathExpression = pathExpression;
        }
    }
}
