// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nsxt.Outputs
{

    [OutputType]
    public sealed class PolicyTier0GatewayHAVIPConfigConfig
    {
        public readonly bool? Enabled;
        public readonly ImmutableArray<string> ExternalInterfacePaths;
        public readonly ImmutableArray<string> VipSubnets;

        [OutputConstructor]
        private PolicyTier0GatewayHAVIPConfigConfig(
            bool? enabled,

            ImmutableArray<string> externalInterfacePaths,

            ImmutableArray<string> vipSubnets)
        {
            Enabled = enabled;
            ExternalInterfacePaths = externalInterfacePaths;
            VipSubnets = vipSubnets;
        }
    }
}
