# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Union
from . import utilities, tables


class IPBlockSubnet(pulumi.CustomResource):
    allocation_ranges: pulumi.Output[list]
    """
    A collection of IPv4 Pool Ranges

      * `end` (`str`)
      * `start` (`str`)
    """
    block_id: pulumi.Output[str]
    """
    Block id for which the subnet is created
    """
    cidr: pulumi.Output[str]
    """
    Represents network address and the prefix length which will be associated with a layer-2 broadcast domain
    """
    description: pulumi.Output[str]
    """
    Description of this resource
    """
    display_name: pulumi.Output[str]
    """
    The display name of this resource. Defaults to ID if not set
    """
    revision: pulumi.Output[float]
    """
    The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
    changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
    operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
    """
    size: pulumi.Output[float]
    """
    Represents the size or number of ip addresses in the subnet
    """
    tags: pulumi.Output[list]
    """
    Set of opaque identifiers meaningful to the user

      * `scope` (`str`)
      * `tag` (`str`)
    """
    def __init__(__self__, resource_name, opts=None, block_id=None, description=None, display_name=None, size=None, tags=None, __props__=None, __name__=None, __opts__=None):
        """
        Create a IPBlockSubnet resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] block_id: Block id for which the subnet is created
        :param pulumi.Input[str] description: Description of this resource
        :param pulumi.Input[str] display_name: The display name of this resource. Defaults to ID if not set
        :param pulumi.Input[float] size: Represents the size or number of ip addresses in the subnet
        :param pulumi.Input[list] tags: Set of opaque identifiers meaningful to the user

        The **tags** object supports the following:

          * `scope` (`pulumi.Input[str]`)
          * `tag` (`pulumi.Input[str]`)
        """
        if __name__ is not None:
            warnings.warn("explicit use of __name__ is deprecated", DeprecationWarning)
            resource_name = __name__
        if __opts__ is not None:
            warnings.warn("explicit use of __opts__ is deprecated, use 'opts' instead", DeprecationWarning)
            opts = __opts__
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = utilities.get_version()
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = dict()

            if block_id is None:
                raise TypeError("Missing required property 'block_id'")
            __props__['block_id'] = block_id
            __props__['description'] = description
            __props__['display_name'] = display_name
            if size is None:
                raise TypeError("Missing required property 'size'")
            __props__['size'] = size
            __props__['tags'] = tags
            __props__['allocation_ranges'] = None
            __props__['cidr'] = None
            __props__['revision'] = None
        super(IPBlockSubnet, __self__).__init__(
            'nsxt:index/iPBlockSubnet:IPBlockSubnet',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name, id, opts=None, allocation_ranges=None, block_id=None, cidr=None, description=None, display_name=None, revision=None, size=None, tags=None):
        """
        Get an existing IPBlockSubnet resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param str id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[list] allocation_ranges: A collection of IPv4 Pool Ranges
        :param pulumi.Input[str] block_id: Block id for which the subnet is created
        :param pulumi.Input[str] cidr: Represents network address and the prefix length which will be associated with a layer-2 broadcast domain
        :param pulumi.Input[str] description: Description of this resource
        :param pulumi.Input[str] display_name: The display name of this resource. Defaults to ID if not set
        :param pulumi.Input[float] revision: The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
               changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
               operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
        :param pulumi.Input[float] size: Represents the size or number of ip addresses in the subnet
        :param pulumi.Input[list] tags: Set of opaque identifiers meaningful to the user

        The **allocation_ranges** object supports the following:

          * `end` (`pulumi.Input[str]`)
          * `start` (`pulumi.Input[str]`)

        The **tags** object supports the following:

          * `scope` (`pulumi.Input[str]`)
          * `tag` (`pulumi.Input[str]`)
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = dict()

        __props__["allocation_ranges"] = allocation_ranges
        __props__["block_id"] = block_id
        __props__["cidr"] = cidr
        __props__["description"] = description
        __props__["display_name"] = display_name
        __props__["revision"] = revision
        __props__["size"] = size
        __props__["tags"] = tags
        return IPBlockSubnet(resource_name, opts=opts, __props__=__props__)

    def translate_output_property(self, prop):
        return tables._CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop

    def translate_input_property(self, prop):
        return tables._SNAKE_TO_CAMEL_CASE_TABLE.get(prop) or prop
