# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Union
from . import utilities, tables


class LogicalTier1Router(pulumi.CustomResource):
    advertise_config_revision: pulumi.Output[float]
    """
    The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
    changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
    operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
    """
    advertise_connected_routes: pulumi.Output[bool]
    """
    Enable connected NSX routes advertisement
    """
    advertise_lb_snat_ip_routes: pulumi.Output[bool]
    """
    Enable LB SNAT IP routes advertisement
    """
    advertise_lb_vip_routes: pulumi.Output[bool]
    """
    Enable LB VIP routes advertisement
    """
    advertise_nat_routes: pulumi.Output[bool]
    """
    Enable NAT routes advertisement
    """
    advertise_static_routes: pulumi.Output[bool]
    """
    Enable static routes advertisement
    """
    description: pulumi.Output[str]
    """
    Description of this resource
    """
    display_name: pulumi.Output[str]
    """
    The display name of this resource. Defaults to ID if not set
    """
    edge_cluster_id: pulumi.Output[str]
    """
    Edge Cluster Id
    """
    enable_router_advertisement: pulumi.Output[bool]
    """
    Enable router advertisement
    """
    failover_mode: pulumi.Output[str]
    """
    Failover mode which determines whether the preferred service router instance for given logical router will preempt the
    peer
    """
    firewall_sections: pulumi.Output[list]
    """
    List of Firewall sections related to the logical router

      * `isValid` (`bool`)
      * `targetDisplayName` (`str`)
      * `targetId` (`str`)
      * `targetType` (`str`)
    """
    revision: pulumi.Output[float]
    """
    The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
    changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
    operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
    """
    tags: pulumi.Output[list]
    """
    Set of opaque identifiers meaningful to the user

      * `scope` (`str`)
      * `tag` (`str`)
    """
    def __init__(__self__, resource_name, opts=None, advertise_connected_routes=None, advertise_lb_snat_ip_routes=None, advertise_lb_vip_routes=None, advertise_nat_routes=None, advertise_static_routes=None, description=None, display_name=None, edge_cluster_id=None, enable_router_advertisement=None, failover_mode=None, firewall_sections=None, tags=None, __props__=None, __name__=None, __opts__=None):
        """
        Create a LogicalTier1Router resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[bool] advertise_connected_routes: Enable connected NSX routes advertisement
        :param pulumi.Input[bool] advertise_lb_snat_ip_routes: Enable LB SNAT IP routes advertisement
        :param pulumi.Input[bool] advertise_lb_vip_routes: Enable LB VIP routes advertisement
        :param pulumi.Input[bool] advertise_nat_routes: Enable NAT routes advertisement
        :param pulumi.Input[bool] advertise_static_routes: Enable static routes advertisement
        :param pulumi.Input[str] description: Description of this resource
        :param pulumi.Input[str] display_name: The display name of this resource. Defaults to ID if not set
        :param pulumi.Input[str] edge_cluster_id: Edge Cluster Id
        :param pulumi.Input[bool] enable_router_advertisement: Enable router advertisement
        :param pulumi.Input[str] failover_mode: Failover mode which determines whether the preferred service router instance for given logical router will preempt the
               peer
        :param pulumi.Input[list] firewall_sections: List of Firewall sections related to the logical router
        :param pulumi.Input[list] tags: Set of opaque identifiers meaningful to the user

        The **firewall_sections** object supports the following:

          * `isValid` (`pulumi.Input[bool]`)
          * `targetDisplayName` (`pulumi.Input[str]`)
          * `targetId` (`pulumi.Input[str]`)
          * `targetType` (`pulumi.Input[str]`)

        The **tags** object supports the following:

          * `scope` (`pulumi.Input[str]`)
          * `tag` (`pulumi.Input[str]`)
        """
        if __name__ is not None:
            warnings.warn("explicit use of __name__ is deprecated", DeprecationWarning)
            resource_name = __name__
        if __opts__ is not None:
            warnings.warn("explicit use of __opts__ is deprecated, use 'opts' instead", DeprecationWarning)
            opts = __opts__
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = utilities.get_version()
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = dict()

            __props__['advertise_connected_routes'] = advertise_connected_routes
            __props__['advertise_lb_snat_ip_routes'] = advertise_lb_snat_ip_routes
            __props__['advertise_lb_vip_routes'] = advertise_lb_vip_routes
            __props__['advertise_nat_routes'] = advertise_nat_routes
            __props__['advertise_static_routes'] = advertise_static_routes
            __props__['description'] = description
            __props__['display_name'] = display_name
            __props__['edge_cluster_id'] = edge_cluster_id
            __props__['enable_router_advertisement'] = enable_router_advertisement
            __props__['failover_mode'] = failover_mode
            __props__['firewall_sections'] = firewall_sections
            __props__['tags'] = tags
            __props__['advertise_config_revision'] = None
            __props__['revision'] = None
        super(LogicalTier1Router, __self__).__init__(
            'nsxt:index/logicalTier1Router:LogicalTier1Router',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name, id, opts=None, advertise_config_revision=None, advertise_connected_routes=None, advertise_lb_snat_ip_routes=None, advertise_lb_vip_routes=None, advertise_nat_routes=None, advertise_static_routes=None, description=None, display_name=None, edge_cluster_id=None, enable_router_advertisement=None, failover_mode=None, firewall_sections=None, revision=None, tags=None):
        """
        Get an existing LogicalTier1Router resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param str id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[float] advertise_config_revision: The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
               changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
               operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
        :param pulumi.Input[bool] advertise_connected_routes: Enable connected NSX routes advertisement
        :param pulumi.Input[bool] advertise_lb_snat_ip_routes: Enable LB SNAT IP routes advertisement
        :param pulumi.Input[bool] advertise_lb_vip_routes: Enable LB VIP routes advertisement
        :param pulumi.Input[bool] advertise_nat_routes: Enable NAT routes advertisement
        :param pulumi.Input[bool] advertise_static_routes: Enable static routes advertisement
        :param pulumi.Input[str] description: Description of this resource
        :param pulumi.Input[str] display_name: The display name of this resource. Defaults to ID if not set
        :param pulumi.Input[str] edge_cluster_id: Edge Cluster Id
        :param pulumi.Input[bool] enable_router_advertisement: Enable router advertisement
        :param pulumi.Input[str] failover_mode: Failover mode which determines whether the preferred service router instance for given logical router will preempt the
               peer
        :param pulumi.Input[list] firewall_sections: List of Firewall sections related to the logical router
        :param pulumi.Input[float] revision: The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
               changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
               operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
        :param pulumi.Input[list] tags: Set of opaque identifiers meaningful to the user

        The **firewall_sections** object supports the following:

          * `isValid` (`pulumi.Input[bool]`)
          * `targetDisplayName` (`pulumi.Input[str]`)
          * `targetId` (`pulumi.Input[str]`)
          * `targetType` (`pulumi.Input[str]`)

        The **tags** object supports the following:

          * `scope` (`pulumi.Input[str]`)
          * `tag` (`pulumi.Input[str]`)
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = dict()

        __props__["advertise_config_revision"] = advertise_config_revision
        __props__["advertise_connected_routes"] = advertise_connected_routes
        __props__["advertise_lb_snat_ip_routes"] = advertise_lb_snat_ip_routes
        __props__["advertise_lb_vip_routes"] = advertise_lb_vip_routes
        __props__["advertise_nat_routes"] = advertise_nat_routes
        __props__["advertise_static_routes"] = advertise_static_routes
        __props__["description"] = description
        __props__["display_name"] = display_name
        __props__["edge_cluster_id"] = edge_cluster_id
        __props__["enable_router_advertisement"] = enable_router_advertisement
        __props__["failover_mode"] = failover_mode
        __props__["firewall_sections"] = firewall_sections
        __props__["revision"] = revision
        __props__["tags"] = tags
        return LogicalTier1Router(resource_name, opts=opts, __props__=__props__)

    def translate_output_property(self, prop):
        return tables._CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop

    def translate_input_property(self, prop):
        return tables._SNAKE_TO_CAMEL_CASE_TABLE.get(prop) or prop
