# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Union
from . import utilities, tables


class NATRule(pulumi.CustomResource):
    action: pulumi.Output[str]
    """
    The action for the NAT Rule
    """
    description: pulumi.Output[str]
    """
    Description of this resource
    """
    display_name: pulumi.Output[str]
    """
    The display name of this resource. Defaults to ID if not set
    """
    enabled: pulumi.Output[bool]
    """
    enable/disable the rule
    """
    logging: pulumi.Output[bool]
    """
    enable/disable the logging of rule
    """
    logical_router_id: pulumi.Output[str]
    """
    Logical router id
    """
    match_destination_network: pulumi.Output[str]
    """
    IP Address | CIDR
    """
    match_source_network: pulumi.Output[str]
    """
    IP Address | CIDR
    """
    nat_pass: pulumi.Output[bool]
    """
    A boolean flag which reflects whether the following firewall stage will be skipped
    """
    revision: pulumi.Output[float]
    """
    The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
    changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
    operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
    """
    rule_priority: pulumi.Output[float]
    """
    The priority of the rule (ascending). Valid range [0-2147483647]
    """
    tags: pulumi.Output[list]
    """
    Set of opaque identifiers meaningful to the user

      * `scope` (`str`)
      * `tag` (`str`)
    """
    translated_network: pulumi.Output[str]
    """
    IP Address | IP Range | CIDR
    """
    translated_ports: pulumi.Output[str]
    """
    port number or port range. DNAT only
    """
    def __init__(__self__, resource_name, opts=None, action=None, description=None, display_name=None, enabled=None, logging=None, logical_router_id=None, match_destination_network=None, match_source_network=None, nat_pass=None, rule_priority=None, tags=None, translated_network=None, translated_ports=None, __props__=None, __name__=None, __opts__=None):
        """
        Create a NATRule resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] action: The action for the NAT Rule
        :param pulumi.Input[str] description: Description of this resource
        :param pulumi.Input[str] display_name: The display name of this resource. Defaults to ID if not set
        :param pulumi.Input[bool] enabled: enable/disable the rule
        :param pulumi.Input[bool] logging: enable/disable the logging of rule
        :param pulumi.Input[str] logical_router_id: Logical router id
        :param pulumi.Input[str] match_destination_network: IP Address | CIDR
        :param pulumi.Input[str] match_source_network: IP Address | CIDR
        :param pulumi.Input[bool] nat_pass: A boolean flag which reflects whether the following firewall stage will be skipped
        :param pulumi.Input[float] rule_priority: The priority of the rule (ascending). Valid range [0-2147483647]
        :param pulumi.Input[list] tags: Set of opaque identifiers meaningful to the user
        :param pulumi.Input[str] translated_network: IP Address | IP Range | CIDR
        :param pulumi.Input[str] translated_ports: port number or port range. DNAT only

        The **tags** object supports the following:

          * `scope` (`pulumi.Input[str]`)
          * `tag` (`pulumi.Input[str]`)
        """
        if __name__ is not None:
            warnings.warn("explicit use of __name__ is deprecated", DeprecationWarning)
            resource_name = __name__
        if __opts__ is not None:
            warnings.warn("explicit use of __opts__ is deprecated, use 'opts' instead", DeprecationWarning)
            opts = __opts__
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = utilities.get_version()
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = dict()

            if action is None:
                raise TypeError("Missing required property 'action'")
            __props__['action'] = action
            __props__['description'] = description
            __props__['display_name'] = display_name
            __props__['enabled'] = enabled
            __props__['logging'] = logging
            if logical_router_id is None:
                raise TypeError("Missing required property 'logical_router_id'")
            __props__['logical_router_id'] = logical_router_id
            __props__['match_destination_network'] = match_destination_network
            __props__['match_source_network'] = match_source_network
            __props__['nat_pass'] = nat_pass
            __props__['rule_priority'] = rule_priority
            __props__['tags'] = tags
            __props__['translated_network'] = translated_network
            __props__['translated_ports'] = translated_ports
            __props__['revision'] = None
        super(NATRule, __self__).__init__(
            'nsxt:index/nATRule:NATRule',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name, id, opts=None, action=None, description=None, display_name=None, enabled=None, logging=None, logical_router_id=None, match_destination_network=None, match_source_network=None, nat_pass=None, revision=None, rule_priority=None, tags=None, translated_network=None, translated_ports=None):
        """
        Get an existing NATRule resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param str id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] action: The action for the NAT Rule
        :param pulumi.Input[str] description: Description of this resource
        :param pulumi.Input[str] display_name: The display name of this resource. Defaults to ID if not set
        :param pulumi.Input[bool] enabled: enable/disable the rule
        :param pulumi.Input[bool] logging: enable/disable the logging of rule
        :param pulumi.Input[str] logical_router_id: Logical router id
        :param pulumi.Input[str] match_destination_network: IP Address | CIDR
        :param pulumi.Input[str] match_source_network: IP Address | CIDR
        :param pulumi.Input[bool] nat_pass: A boolean flag which reflects whether the following firewall stage will be skipped
        :param pulumi.Input[float] revision: The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
               changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
               operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
        :param pulumi.Input[float] rule_priority: The priority of the rule (ascending). Valid range [0-2147483647]
        :param pulumi.Input[list] tags: Set of opaque identifiers meaningful to the user
        :param pulumi.Input[str] translated_network: IP Address | IP Range | CIDR
        :param pulumi.Input[str] translated_ports: port number or port range. DNAT only

        The **tags** object supports the following:

          * `scope` (`pulumi.Input[str]`)
          * `tag` (`pulumi.Input[str]`)
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = dict()

        __props__["action"] = action
        __props__["description"] = description
        __props__["display_name"] = display_name
        __props__["enabled"] = enabled
        __props__["logging"] = logging
        __props__["logical_router_id"] = logical_router_id
        __props__["match_destination_network"] = match_destination_network
        __props__["match_source_network"] = match_source_network
        __props__["nat_pass"] = nat_pass
        __props__["revision"] = revision
        __props__["rule_priority"] = rule_priority
        __props__["tags"] = tags
        __props__["translated_network"] = translated_network
        __props__["translated_ports"] = translated_ports
        return NATRule(resource_name, opts=opts, __props__=__props__)

    def translate_output_property(self, prop):
        return tables._CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop

    def translate_input_property(self, prop):
        return tables._SNAKE_TO_CAMEL_CASE_TABLE.get(prop) or prop
