// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nsxt.Inputs
{

    public sealed class LBHTTPResponseRewriteRuleUriArgumentsConditionArgs : Pulumi.ResourceArgs
    {
        [Input("caseSensitive")]
        public Input<bool>? CaseSensitive { get; set; }

        [Input("inverse")]
        public Input<bool>? Inverse { get; set; }

        [Input("matchType", required: true)]
        public Input<string> MatchType { get; set; } = null!;

        [Input("uriArguments", required: true)]
        public Input<string> UriArguments { get; set; } = null!;

        public LBHTTPResponseRewriteRuleUriArgumentsConditionArgs()
        {
        }
    }
}
