// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nsxt.Inputs
{

    public sealed class LBHTTPVirtualServerServerSslGetArgs : Pulumi.ResourceArgs
    {
        [Input("caIds")]
        private InputList<string>? _caIds;
        public InputList<string> CaIds
        {
            get => _caIds ?? (_caIds = new InputList<string>());
            set => _caIds = value;
        }

        [Input("certificateChainDepth")]
        public Input<int>? CertificateChainDepth { get; set; }

        [Input("clientCertificateId")]
        public Input<string>? ClientCertificateId { get; set; }

        [Input("crlIds")]
        private InputList<string>? _crlIds;
        public InputList<string> CrlIds
        {
            get => _crlIds ?? (_crlIds = new InputList<string>());
            set => _crlIds = value;
        }

        [Input("serverAuth")]
        public Input<bool>? ServerAuth { get; set; }

        [Input("serverSslProfileId", required: true)]
        public Input<string> ServerSslProfileId { get; set; } = null!;

        public LBHTTPVirtualServerServerSslGetArgs()
        {
        }
    }
}
