// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nsxt.Inputs
{

    public sealed class LBHTTPForwardingRuleHttpRedirectActionGetArgs : Pulumi.ResourceArgs
    {
        [Input("redirectStatus", required: true)]
        public Input<string> RedirectStatus { get; set; } = null!;

        [Input("redirectUrl", required: true)]
        public Input<string> RedirectUrl { get; set; } = null!;

        public LBHTTPForwardingRuleHttpRedirectActionGetArgs()
        {
        }
    }
}
