// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nsxt.Inputs
{

    public sealed class NSroupMembershipCriteriaArgs : Pulumi.ResourceArgs
    {
        [Input("scope")]
        public Input<string>? Scope { get; set; }

        [Input("scopeOp")]
        public Input<string>? ScopeOp { get; set; }

        [Input("tag")]
        public Input<string>? Tag { get; set; }

        [Input("tagOp")]
        public Input<string>? TagOp { get; set; }

        [Input("targetType", required: true)]
        public Input<string> TargetType { get; set; } = null!;

        public NSroupMembershipCriteriaArgs()
        {
        }
    }
}
