// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nsxt.Inputs
{

    public sealed class PolicyGroupCriteriaArgs : Pulumi.ResourceArgs
    {
        [Input("conditions")]
        private InputList<Inputs.PolicyGroupCriteriaConditionArgs>? _conditions;
        public InputList<Inputs.PolicyGroupCriteriaConditionArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Inputs.PolicyGroupCriteriaConditionArgs>());
            set => _conditions = value;
        }

        [Input("ipaddressExpression")]
        public Input<Inputs.PolicyGroupCriteriaIpaddressExpressionArgs>? IpaddressExpression { get; set; }

        [Input("macaddressExpression")]
        public Input<Inputs.PolicyGroupCriteriaMacaddressExpressionArgs>? MacaddressExpression { get; set; }

        [Input("pathExpression")]
        public Input<Inputs.PolicyGroupCriteriaPathExpressionArgs>? PathExpression { get; set; }

        public PolicyGroupCriteriaArgs()
        {
        }
    }
}
