// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getPolicyGatewayPolicy(args?: GetPolicyGatewayPolicyArgs, opts?: pulumi.InvokeOptions): Promise<GetPolicyGatewayPolicyResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("nsxt:index/getPolicyGatewayPolicy:getPolicyGatewayPolicy", {
        "category": args.category,
        "description": args.description,
        "displayName": args.displayName,
        "domain": args.domain,
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getPolicyGatewayPolicy.
 */
export interface GetPolicyGatewayPolicyArgs {
    readonly category?: string;
    readonly description?: string;
    readonly displayName?: string;
    readonly domain?: string;
    readonly id?: string;
}

/**
 * A collection of values returned by getPolicyGatewayPolicy.
 */
export interface GetPolicyGatewayPolicyResult {
    readonly category: string;
    readonly description: string;
    readonly displayName: string;
    readonly domain?: string;
    readonly id: string;
    readonly path: string;
}
