// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getPolicyRealizationInfo(args: GetPolicyRealizationInfoArgs, opts?: pulumi.InvokeOptions): Promise<GetPolicyRealizationInfoResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("nsxt:index/getPolicyRealizationInfo:getPolicyRealizationInfo", {
        "entityType": args.entityType,
        "id": args.id,
        "path": args.path,
        "sitePath": args.sitePath,
    }, opts);
}

/**
 * A collection of arguments for invoking getPolicyRealizationInfo.
 */
export interface GetPolicyRealizationInfoArgs {
    readonly entityType?: string;
    readonly id?: string;
    readonly path: string;
    readonly sitePath?: string;
}

/**
 * A collection of values returned by getPolicyRealizationInfo.
 */
export interface GetPolicyRealizationInfoResult {
    readonly entityType: string;
    readonly id: string;
    readonly path: string;
    readonly realizedId: string;
    readonly sitePath?: string;
    readonly state: string;
}
