// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class LBServerSSLProfile extends pulumi.CustomResource {
    /**
     * Get an existing LBServerSSLProfile resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LBServerSSLProfileState, opts?: pulumi.CustomResourceOptions): LBServerSSLProfile {
        return new LBServerSSLProfile(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'nsxt:index/lBServerSSLProfile:LBServerSSLProfile';

    /**
     * Returns true if the given object is an instance of LBServerSSLProfile.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LBServerSSLProfile {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LBServerSSLProfile.__pulumiType;
    }

    /**
     * Supported SSL cipher list
     */
    public readonly ciphers!: pulumi.Output<string[]>;
    /**
     * Description of this resource
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * The display name of this resource. Defaults to ID if not set
     */
    public readonly displayName!: pulumi.Output<string>;
    /**
     * This flag is set to true when all the ciphers and protocols are secure. It is set to false when one of the ciphers or
     * protocols is insecure
     */
    public /*out*/ readonly isSecure!: pulumi.Output<boolean>;
    /**
     * SSL versions TLS1.1 and TLS1.2 are supported and enabled by default. SSLv2, SSLv3, and TLS1.0 are supported, but
     * disabled by default
     */
    public readonly protocols!: pulumi.Output<string[]>;
    /**
     * The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
     * changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
     * operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
     */
    public /*out*/ readonly revision!: pulumi.Output<number>;
    /**
     * Reuse previously negotiated security parameters during handshake
     */
    public readonly sessionCacheEnabled!: pulumi.Output<boolean | undefined>;
    /**
     * Set of opaque identifiers meaningful to the user
     */
    public readonly tags!: pulumi.Output<outputs.LBServerSSLProfileTag[] | undefined>;

    /**
     * Create a LBServerSSLProfile resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: LBServerSSLProfileArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LBServerSSLProfileArgs | LBServerSSLProfileState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as LBServerSSLProfileState | undefined;
            inputs["ciphers"] = state ? state.ciphers : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["displayName"] = state ? state.displayName : undefined;
            inputs["isSecure"] = state ? state.isSecure : undefined;
            inputs["protocols"] = state ? state.protocols : undefined;
            inputs["revision"] = state ? state.revision : undefined;
            inputs["sessionCacheEnabled"] = state ? state.sessionCacheEnabled : undefined;
            inputs["tags"] = state ? state.tags : undefined;
        } else {
            const args = argsOrState as LBServerSSLProfileArgs | undefined;
            inputs["ciphers"] = args ? args.ciphers : undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["displayName"] = args ? args.displayName : undefined;
            inputs["protocols"] = args ? args.protocols : undefined;
            inputs["sessionCacheEnabled"] = args ? args.sessionCacheEnabled : undefined;
            inputs["tags"] = args ? args.tags : undefined;
            inputs["isSecure"] = undefined /*out*/;
            inputs["revision"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(LBServerSSLProfile.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering LBServerSSLProfile resources.
 */
export interface LBServerSSLProfileState {
    /**
     * Supported SSL cipher list
     */
    readonly ciphers?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Description of this resource
     */
    readonly description?: pulumi.Input<string>;
    /**
     * The display name of this resource. Defaults to ID if not set
     */
    readonly displayName?: pulumi.Input<string>;
    /**
     * This flag is set to true when all the ciphers and protocols are secure. It is set to false when one of the ciphers or
     * protocols is insecure
     */
    readonly isSecure?: pulumi.Input<boolean>;
    /**
     * SSL versions TLS1.1 and TLS1.2 are supported and enabled by default. SSLv2, SSLv3, and TLS1.0 are supported, but
     * disabled by default
     */
    readonly protocols?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
     * changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
     * operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
     */
    readonly revision?: pulumi.Input<number>;
    /**
     * Reuse previously negotiated security parameters during handshake
     */
    readonly sessionCacheEnabled?: pulumi.Input<boolean>;
    /**
     * Set of opaque identifiers meaningful to the user
     */
    readonly tags?: pulumi.Input<pulumi.Input<inputs.LBServerSSLProfileTag>[]>;
}

/**
 * The set of arguments for constructing a LBServerSSLProfile resource.
 */
export interface LBServerSSLProfileArgs {
    /**
     * Supported SSL cipher list
     */
    readonly ciphers?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Description of this resource
     */
    readonly description?: pulumi.Input<string>;
    /**
     * The display name of this resource. Defaults to ID if not set
     */
    readonly displayName?: pulumi.Input<string>;
    /**
     * SSL versions TLS1.1 and TLS1.2 are supported and enabled by default. SSLv2, SSLv3, and TLS1.0 are supported, but
     * disabled by default
     */
    readonly protocols?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Reuse previously negotiated security parameters during handshake
     */
    readonly sessionCacheEnabled?: pulumi.Input<boolean>;
    /**
     * Set of opaque identifiers meaningful to the user
     */
    readonly tags?: pulumi.Input<pulumi.Input<inputs.LBServerSSLProfileTag>[]>;
}
