// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class LBSourceIPPersistenceProfile extends pulumi.CustomResource {
    /**
     * Get an existing LBSourceIPPersistenceProfile resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LBSourceIPPersistenceProfileState, opts?: pulumi.CustomResourceOptions): LBSourceIPPersistenceProfile {
        return new LBSourceIPPersistenceProfile(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'nsxt:index/lBSourceIPPersistenceProfile:LBSourceIPPersistenceProfile';

    /**
     * Returns true if the given object is an instance of LBSourceIPPersistenceProfile.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LBSourceIPPersistenceProfile {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LBSourceIPPersistenceProfile.__pulumiType;
    }

    /**
     * Description of this resource
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * The display name of this resource. Defaults to ID if not set
     */
    public readonly displayName!: pulumi.Output<string>;
    /**
     * A boolean flag which reflects whether persistence entries will be synchronized to the HA peer
     */
    public readonly haPersistenceMirroring!: pulumi.Output<boolean | undefined>;
    /**
     * A boolean flag which reflects whether the cookie persistence is private or shared
     */
    public readonly persistenceShared!: pulumi.Output<boolean | undefined>;
    /**
     * A boolean flag which reflects whether entries will be purged when the persistence table is full
     */
    public readonly purgeWhenFull!: pulumi.Output<boolean | undefined>;
    /**
     * The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
     * changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
     * operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
     */
    public /*out*/ readonly revision!: pulumi.Output<number>;
    /**
     * Set of opaque identifiers meaningful to the user
     */
    public readonly tags!: pulumi.Output<outputs.LBSourceIPPersistenceProfileTag[] | undefined>;
    /**
     * Persistence expiration time in seconds, counted from the time all the connections are completed
     */
    public readonly timeout!: pulumi.Output<number | undefined>;

    /**
     * Create a LBSourceIPPersistenceProfile resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: LBSourceIPPersistenceProfileArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LBSourceIPPersistenceProfileArgs | LBSourceIPPersistenceProfileState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as LBSourceIPPersistenceProfileState | undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["displayName"] = state ? state.displayName : undefined;
            inputs["haPersistenceMirroring"] = state ? state.haPersistenceMirroring : undefined;
            inputs["persistenceShared"] = state ? state.persistenceShared : undefined;
            inputs["purgeWhenFull"] = state ? state.purgeWhenFull : undefined;
            inputs["revision"] = state ? state.revision : undefined;
            inputs["tags"] = state ? state.tags : undefined;
            inputs["timeout"] = state ? state.timeout : undefined;
        } else {
            const args = argsOrState as LBSourceIPPersistenceProfileArgs | undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["displayName"] = args ? args.displayName : undefined;
            inputs["haPersistenceMirroring"] = args ? args.haPersistenceMirroring : undefined;
            inputs["persistenceShared"] = args ? args.persistenceShared : undefined;
            inputs["purgeWhenFull"] = args ? args.purgeWhenFull : undefined;
            inputs["tags"] = args ? args.tags : undefined;
            inputs["timeout"] = args ? args.timeout : undefined;
            inputs["revision"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(LBSourceIPPersistenceProfile.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering LBSourceIPPersistenceProfile resources.
 */
export interface LBSourceIPPersistenceProfileState {
    /**
     * Description of this resource
     */
    readonly description?: pulumi.Input<string>;
    /**
     * The display name of this resource. Defaults to ID if not set
     */
    readonly displayName?: pulumi.Input<string>;
    /**
     * A boolean flag which reflects whether persistence entries will be synchronized to the HA peer
     */
    readonly haPersistenceMirroring?: pulumi.Input<boolean>;
    /**
     * A boolean flag which reflects whether the cookie persistence is private or shared
     */
    readonly persistenceShared?: pulumi.Input<boolean>;
    /**
     * A boolean flag which reflects whether entries will be purged when the persistence table is full
     */
    readonly purgeWhenFull?: pulumi.Input<boolean>;
    /**
     * The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
     * changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
     * operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
     */
    readonly revision?: pulumi.Input<number>;
    /**
     * Set of opaque identifiers meaningful to the user
     */
    readonly tags?: pulumi.Input<pulumi.Input<inputs.LBSourceIPPersistenceProfileTag>[]>;
    /**
     * Persistence expiration time in seconds, counted from the time all the connections are completed
     */
    readonly timeout?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a LBSourceIPPersistenceProfile resource.
 */
export interface LBSourceIPPersistenceProfileArgs {
    /**
     * Description of this resource
     */
    readonly description?: pulumi.Input<string>;
    /**
     * The display name of this resource. Defaults to ID if not set
     */
    readonly displayName?: pulumi.Input<string>;
    /**
     * A boolean flag which reflects whether persistence entries will be synchronized to the HA peer
     */
    readonly haPersistenceMirroring?: pulumi.Input<boolean>;
    /**
     * A boolean flag which reflects whether the cookie persistence is private or shared
     */
    readonly persistenceShared?: pulumi.Input<boolean>;
    /**
     * A boolean flag which reflects whether entries will be purged when the persistence table is full
     */
    readonly purgeWhenFull?: pulumi.Input<boolean>;
    /**
     * Set of opaque identifiers meaningful to the user
     */
    readonly tags?: pulumi.Input<pulumi.Input<inputs.LBSourceIPPersistenceProfileTag>[]>;
    /**
     * Persistence expiration time in seconds, counted from the time all the connections are completed
     */
    readonly timeout?: pulumi.Input<number>;
}
