// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class LogicalTier0Router extends pulumi.CustomResource {
    /**
     * Get an existing LogicalTier0Router resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LogicalTier0RouterState, opts?: pulumi.CustomResourceOptions): LogicalTier0Router {
        return new LogicalTier0Router(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'nsxt:index/logicalTier0Router:LogicalTier0Router';

    /**
     * Returns true if the given object is an instance of LogicalTier0Router.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LogicalTier0Router {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LogicalTier0Router.__pulumiType;
    }

    /**
     * Description of this resource
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * The display name of this resource. Defaults to ID if not set
     */
    public readonly displayName!: pulumi.Output<string>;
    /**
     * Edge Cluster Id
     */
    public readonly edgeClusterId!: pulumi.Output<string>;
    /**
     * Failover mode which determines whether the preferred service router instance for given logical router will preempt the
     * peer
     */
    public readonly failoverMode!: pulumi.Output<string>;
    /**
     * List of Firewall sections related to the logical router
     */
    public readonly firewallSections!: pulumi.Output<outputs.LogicalTier0RouterFirewallSection[]>;
    /**
     * High availability mode
     */
    public readonly highAvailabilityMode!: pulumi.Output<string | undefined>;
    /**
     * The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
     * changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
     * operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
     */
    public /*out*/ readonly revision!: pulumi.Output<number>;
    /**
     * Set of opaque identifiers meaningful to the user
     */
    public readonly tags!: pulumi.Output<outputs.LogicalTier0RouterTag[] | undefined>;

    /**
     * Create a LogicalTier0Router resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LogicalTier0RouterArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LogicalTier0RouterArgs | LogicalTier0RouterState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as LogicalTier0RouterState | undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["displayName"] = state ? state.displayName : undefined;
            inputs["edgeClusterId"] = state ? state.edgeClusterId : undefined;
            inputs["failoverMode"] = state ? state.failoverMode : undefined;
            inputs["firewallSections"] = state ? state.firewallSections : undefined;
            inputs["highAvailabilityMode"] = state ? state.highAvailabilityMode : undefined;
            inputs["revision"] = state ? state.revision : undefined;
            inputs["tags"] = state ? state.tags : undefined;
        } else {
            const args = argsOrState as LogicalTier0RouterArgs | undefined;
            if (!args || args.edgeClusterId === undefined) {
                throw new Error("Missing required property 'edgeClusterId'");
            }
            inputs["description"] = args ? args.description : undefined;
            inputs["displayName"] = args ? args.displayName : undefined;
            inputs["edgeClusterId"] = args ? args.edgeClusterId : undefined;
            inputs["failoverMode"] = args ? args.failoverMode : undefined;
            inputs["firewallSections"] = args ? args.firewallSections : undefined;
            inputs["highAvailabilityMode"] = args ? args.highAvailabilityMode : undefined;
            inputs["tags"] = args ? args.tags : undefined;
            inputs["revision"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(LogicalTier0Router.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering LogicalTier0Router resources.
 */
export interface LogicalTier0RouterState {
    /**
     * Description of this resource
     */
    readonly description?: pulumi.Input<string>;
    /**
     * The display name of this resource. Defaults to ID if not set
     */
    readonly displayName?: pulumi.Input<string>;
    /**
     * Edge Cluster Id
     */
    readonly edgeClusterId?: pulumi.Input<string>;
    /**
     * Failover mode which determines whether the preferred service router instance for given logical router will preempt the
     * peer
     */
    readonly failoverMode?: pulumi.Input<string>;
    /**
     * List of Firewall sections related to the logical router
     */
    readonly firewallSections?: pulumi.Input<pulumi.Input<inputs.LogicalTier0RouterFirewallSection>[]>;
    /**
     * High availability mode
     */
    readonly highAvailabilityMode?: pulumi.Input<string>;
    /**
     * The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
     * changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
     * operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
     */
    readonly revision?: pulumi.Input<number>;
    /**
     * Set of opaque identifiers meaningful to the user
     */
    readonly tags?: pulumi.Input<pulumi.Input<inputs.LogicalTier0RouterTag>[]>;
}

/**
 * The set of arguments for constructing a LogicalTier0Router resource.
 */
export interface LogicalTier0RouterArgs {
    /**
     * Description of this resource
     */
    readonly description?: pulumi.Input<string>;
    /**
     * The display name of this resource. Defaults to ID if not set
     */
    readonly displayName?: pulumi.Input<string>;
    /**
     * Edge Cluster Id
     */
    readonly edgeClusterId: pulumi.Input<string>;
    /**
     * Failover mode which determines whether the preferred service router instance for given logical router will preempt the
     * peer
     */
    readonly failoverMode?: pulumi.Input<string>;
    /**
     * List of Firewall sections related to the logical router
     */
    readonly firewallSections?: pulumi.Input<pulumi.Input<inputs.LogicalTier0RouterFirewallSection>[]>;
    /**
     * High availability mode
     */
    readonly highAvailabilityMode?: pulumi.Input<string>;
    /**
     * Set of opaque identifiers meaningful to the user
     */
    readonly tags?: pulumi.Input<pulumi.Input<inputs.LogicalTier0RouterTag>[]>;
}
