// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class PolicyService extends pulumi.CustomResource {
    /**
     * Get an existing PolicyService resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PolicyServiceState, opts?: pulumi.CustomResourceOptions): PolicyService {
        return new PolicyService(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'nsxt:index/policyService:PolicyService';

    /**
     * Returns true if the given object is an instance of PolicyService.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PolicyService {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PolicyService.__pulumiType;
    }

    /**
     * Algorithm type service entry
     */
    public readonly algorithmEntries!: pulumi.Output<outputs.PolicyServiceAlgorithmEntry[] | undefined>;
    /**
     * Description for this resource
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * Display name for this resource
     */
    public readonly displayName!: pulumi.Output<string>;
    /**
     * Ether type service entry
     */
    public readonly etherTypeEntries!: pulumi.Output<outputs.PolicyServiceEtherTypeEntry[] | undefined>;
    /**
     * ICMP type service entry
     */
    public readonly icmpEntries!: pulumi.Output<outputs.PolicyServiceIcmpEntry[] | undefined>;
    /**
     * IGMP type service entry
     */
    public readonly igmpEntries!: pulumi.Output<outputs.PolicyServiceIgmpEntry[] | undefined>;
    /**
     * IP Protocol type service entry
     */
    public readonly ipProtocolEntries!: pulumi.Output<outputs.PolicyServiceIpProtocolEntry[] | undefined>;
    /**
     * L4 port set type service entry
     */
    public readonly l4PortSetEntries!: pulumi.Output<outputs.PolicyServiceL4PortSetEntry[] | undefined>;
    /**
     * NSX ID for this resource
     */
    public readonly nsxId!: pulumi.Output<string>;
    /**
     * Policy path for this resource
     */
    public /*out*/ readonly path!: pulumi.Output<string>;
    /**
     * The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
     * changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
     * operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
     */
    public /*out*/ readonly revision!: pulumi.Output<number>;
    /**
     * Set of opaque identifiers meaningful to the user
     */
    public readonly tags!: pulumi.Output<outputs.PolicyServiceTag[] | undefined>;

    /**
     * Create a PolicyService resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PolicyServiceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PolicyServiceArgs | PolicyServiceState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as PolicyServiceState | undefined;
            inputs["algorithmEntries"] = state ? state.algorithmEntries : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["displayName"] = state ? state.displayName : undefined;
            inputs["etherTypeEntries"] = state ? state.etherTypeEntries : undefined;
            inputs["icmpEntries"] = state ? state.icmpEntries : undefined;
            inputs["igmpEntries"] = state ? state.igmpEntries : undefined;
            inputs["ipProtocolEntries"] = state ? state.ipProtocolEntries : undefined;
            inputs["l4PortSetEntries"] = state ? state.l4PortSetEntries : undefined;
            inputs["nsxId"] = state ? state.nsxId : undefined;
            inputs["path"] = state ? state.path : undefined;
            inputs["revision"] = state ? state.revision : undefined;
            inputs["tags"] = state ? state.tags : undefined;
        } else {
            const args = argsOrState as PolicyServiceArgs | undefined;
            if (!args || args.displayName === undefined) {
                throw new Error("Missing required property 'displayName'");
            }
            inputs["algorithmEntries"] = args ? args.algorithmEntries : undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["displayName"] = args ? args.displayName : undefined;
            inputs["etherTypeEntries"] = args ? args.etherTypeEntries : undefined;
            inputs["icmpEntries"] = args ? args.icmpEntries : undefined;
            inputs["igmpEntries"] = args ? args.igmpEntries : undefined;
            inputs["ipProtocolEntries"] = args ? args.ipProtocolEntries : undefined;
            inputs["l4PortSetEntries"] = args ? args.l4PortSetEntries : undefined;
            inputs["nsxId"] = args ? args.nsxId : undefined;
            inputs["tags"] = args ? args.tags : undefined;
            inputs["path"] = undefined /*out*/;
            inputs["revision"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(PolicyService.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering PolicyService resources.
 */
export interface PolicyServiceState {
    /**
     * Algorithm type service entry
     */
    readonly algorithmEntries?: pulumi.Input<pulumi.Input<inputs.PolicyServiceAlgorithmEntry>[]>;
    /**
     * Description for this resource
     */
    readonly description?: pulumi.Input<string>;
    /**
     * Display name for this resource
     */
    readonly displayName?: pulumi.Input<string>;
    /**
     * Ether type service entry
     */
    readonly etherTypeEntries?: pulumi.Input<pulumi.Input<inputs.PolicyServiceEtherTypeEntry>[]>;
    /**
     * ICMP type service entry
     */
    readonly icmpEntries?: pulumi.Input<pulumi.Input<inputs.PolicyServiceIcmpEntry>[]>;
    /**
     * IGMP type service entry
     */
    readonly igmpEntries?: pulumi.Input<pulumi.Input<inputs.PolicyServiceIgmpEntry>[]>;
    /**
     * IP Protocol type service entry
     */
    readonly ipProtocolEntries?: pulumi.Input<pulumi.Input<inputs.PolicyServiceIpProtocolEntry>[]>;
    /**
     * L4 port set type service entry
     */
    readonly l4PortSetEntries?: pulumi.Input<pulumi.Input<inputs.PolicyServiceL4PortSetEntry>[]>;
    /**
     * NSX ID for this resource
     */
    readonly nsxId?: pulumi.Input<string>;
    /**
     * Policy path for this resource
     */
    readonly path?: pulumi.Input<string>;
    /**
     * The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's
     * changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET
     * operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
     */
    readonly revision?: pulumi.Input<number>;
    /**
     * Set of opaque identifiers meaningful to the user
     */
    readonly tags?: pulumi.Input<pulumi.Input<inputs.PolicyServiceTag>[]>;
}

/**
 * The set of arguments for constructing a PolicyService resource.
 */
export interface PolicyServiceArgs {
    /**
     * Algorithm type service entry
     */
    readonly algorithmEntries?: pulumi.Input<pulumi.Input<inputs.PolicyServiceAlgorithmEntry>[]>;
    /**
     * Description for this resource
     */
    readonly description?: pulumi.Input<string>;
    /**
     * Display name for this resource
     */
    readonly displayName: pulumi.Input<string>;
    /**
     * Ether type service entry
     */
    readonly etherTypeEntries?: pulumi.Input<pulumi.Input<inputs.PolicyServiceEtherTypeEntry>[]>;
    /**
     * ICMP type service entry
     */
    readonly icmpEntries?: pulumi.Input<pulumi.Input<inputs.PolicyServiceIcmpEntry>[]>;
    /**
     * IGMP type service entry
     */
    readonly igmpEntries?: pulumi.Input<pulumi.Input<inputs.PolicyServiceIgmpEntry>[]>;
    /**
     * IP Protocol type service entry
     */
    readonly ipProtocolEntries?: pulumi.Input<pulumi.Input<inputs.PolicyServiceIpProtocolEntry>[]>;
    /**
     * L4 port set type service entry
     */
    readonly l4PortSetEntries?: pulumi.Input<pulumi.Input<inputs.PolicyServiceL4PortSetEntry>[]>;
    /**
     * NSX ID for this resource
     */
    readonly nsxId?: pulumi.Input<string>;
    /**
     * Set of opaque identifiers meaningful to the user
     */
    readonly tags?: pulumi.Input<pulumi.Input<inputs.PolicyServiceTag>[]>;
}
